/** Protocol layers. Long-form lore lives in knowledge.js; this file holds labels and live-data notes. */
export const LAYERS = [
  {
    id: "sip-1",
    sip: "SIP-1",
    status: "Implemented",
    knowledge: "sip-1",
    name: { tr: "Blok İşlem", en: "Block Trade", fr: "Block Trade", zh: "大宗交易", ja: "ブロック取引" },
    live: {
      tr: "Aşağıdaki derinlik röntgeni sadece açık defteri gösterir. Blok akışı bu beslemede yok.",
      en: "The depth x-ray below shows the public book only. Block flow is not in this feed.",
      fr: "La radio de profondeur ci-dessous ne montre que le carnet public. Le flux bloc n'y est pas.",
      zh: "下方的深度透视只显示公开订单簿。大宗流不在此数据中。",
      ja: "下のデプスX線は公開板のみを表示します。ブロックフローはこのフィードにありません。",
    },
  },
  {
    id: "sip-2",
    sip: "SIP-2",
    status: "Implemented",
    knowledge: "sip-2",
    name: { tr: "Pozisyon Getirisi", en: "Position Yield", fr: "Rendement de position", zh: "仓位收益", ja: "ポジション利回り" },
    live: {
      tr: "Her piyasanın açık faizi canlı. Getiri ödemeleri açık API'de yayınlanmıyor.",
      en: "Open interest per market is live. Yield payouts are not published on the public API.",
      fr: "L'open interest par marché est en direct. Les paiements de rendement ne sont pas publiés.",
      zh: "各市场的未平仓量是实时的。收益发放不在公开 API 中。",
      ja: "各市場の建玉はライブです。利回りの支払いは公開 API にありません。",
    },
  },
  {
    id: "sip-3",
    sip: "SIP-3",
    status: "Implemented",
    knowledge: "sip-3",
    name: { tr: "DUSD Native Getiri", en: "DUSD Native Yield", fr: "Rendement natif DUSD", zh: "DUSD 原生收益", ja: "DUSD ネイティブ利回り" },
    live: {
      tr: "24 saatlik hacim ücret faaliyetinin göstergesi. Vault TVL burada yok.",
      en: "24h volume is the proxy for fee activity. Vault TVL is not shown here.",
      fr: "Le volume 24h est le proxy de l'activité de frais. Le TVL des vaults n'est pas affiché.",
      zh: "24 小时成交额是手续费活跃度的代理指标。此处不显示金库 TVL。",
      ja: "24時間出来高は手数料活動の代理指標です。Vault の TVL はここには出ません。",
    },
  },
  {
    id: "sip-4",
    sip: "SIP-4",
    status: "Implemented",
    knowledge: "sip-4",
    name: { tr: "Blok Opsiyonlar", en: "Block Options", fr: "Block Options", zh: "大宗期权", ja: "ブロックオプション" },
    live: {
      tr: "Opsiyon envanteri burada yayınlanmıyor. Bu katman protokol anatomisi.",
      en: "Options inventory is not published here. This layer is protocol anatomy.",
      fr: "L'inventaire d'options n'est pas publié ici. Cette couche est de l'anatomie protocolaire.",
      zh: "此处不公布期权库存。这一层是协议解剖。",
      ja: "オプション在庫はここには出ません。この層はプロトコルの解剖図です。",
    },
  },
  {
    id: "sip-5",
    sip: "SIP-5",
    status: "WIP",
    knowledge: "sip-5",
    name: { tr: "Evrensel Piyasalar", en: "Universal Markets", fr: "Marchés universels", zh: "万能市场", ja: "ユニバーサル市場" },
    live: {
      tr: "Yukarıdaki piyasalar canlı listelemeler. Vault bakiyesi gösterilmiyor.",
      en: "The markets above are live listings. No vault balances are shown.",
      fr: "Les marchés ci-dessus sont des listings en direct. Aucun solde de vault n'est affiché.",
      zh: "上方市场是实时上架的。这里不显示金库余额。",
      ja: "上の市場はライブ上場です。Vault 残高は表示しません。",
    },
  },
  {
    id: "sip-5a",
    sip: "SIP-5A",
    status: "Implemented",
    knowledge: "sip-5a",
    name: { tr: "Topluluk Maker Getirisi", en: "Community Maker Yield", fr: "Rendement maker communautaire", zh: "社区做市收益", ja: "コミュニティメイカー利回り" },
    live: {
      tr: "Spread ve defter eğilimi canlı; maker kalitesi tam da burada ölçülüyor.",
      en: "Spread and book bias are live — maker quality is measured exactly here.",
      fr: "Le spread et le biais du carnet sont en direct — la qualité maker se mesure ici.",
      zh: "价差和订单簿偏向是实时的 —— 做市质量正是在这里衡量。",
      ja: "スプレッドと板の偏りはライブで、メイカー品質はまさにここで測られます。",
    },
  },
  {
    id: "sip-5b",
    sip: "SIP-5B",
    status: "Implemented",
    knowledge: "community-vaults",
    name: { tr: "Topluluk Kasaları", en: "Community Vaults", fr: "Vaults communautaires", zh: "社区金库", ja: "コミュニティ Vault" },
    live: {
      tr: "Kasa bakiyeleri açık piyasa beslemesinde yok. Burası vault gezgini değil.",
      en: "Vault balances are not in the public market feed. This is not a vault explorer.",
      fr: "Les soldes de vault ne sont pas dans le flux public. Ce n'est pas un explorateur de vaults.",
      zh: "金库余额不在公开行情数据中。这里不是金库浏览器。",
      ja: "Vault 残高は公開マーケットフィードにありません。ここは Vault エクスプローラーではありません。",
    },
  },
];

/** Wallet-to-first-trade path, straight from the docs. */
export const STEPS = [
  {
    id: "wallet",
    icon: "01",
    title: { tr: "Cüzdanı bağla", en: "Connect a wallet", fr: "Connecte un portefeuille", zh: "连接钱包", ja: "ウォレットを接続" },
    body: {
      tr: "standx.com'da CONNECT WALLET. BNB Chain için Binance Wallet veya MetaMask, Solana için Phantom. Ağ ücreti için cüzdanda biraz BNB ya da SOL bulunsun.",
      en: "Hit CONNECT WALLET on standx.com. Binance Wallet or MetaMask for BNB Chain, Phantom for Solana. Keep a little BNB or SOL for network fees.",
      fr: "Clique sur CONNECT WALLET sur standx.com. Binance Wallet ou MetaMask pour BNB Chain, Phantom pour Solana. Garde un peu de BNB ou SOL pour les frais réseau.",
      zh: "在 standx.com 点击 CONNECT WALLET。BNB Chain 用 Binance Wallet 或 MetaMask，Solana 用 Phantom。钱包里留一点 BNB 或 SOL 付网络费。",
      ja: "standx.com で CONNECT WALLET。BNB Chain は Binance Wallet か MetaMask、Solana は Phantom。ネットワーク手数料用に BNB か SOL を少し残しておきます。",
    },
  },
  {
    id: "mint",
    icon: "02",
    title: { tr: "DUSD bastır", en: "Mint DUSD", fr: "Minte du DUSD", zh: "铸造 DUSD", ja: "DUSD をミント" },
    body: {
      tr: "USDT veya USDC ile 1:1 bastır. Minimum 5 dolar, basım ücreti yok. Ödüller o an işlemeye başlar, stake gerekmez.",
      en: "Mint 1:1 with USDT or USDC. Minimum $5, no minting fee. Rewards start accruing right away, no staking needed.",
      fr: "Minte 1:1 avec USDT ou USDC. Minimum 5 $, aucun frais. Les récompenses courent tout de suite, sans staking.",
      zh: "用 USDT 或 USDC 以 1:1 铸造。最低 5 美元，无铸造费。奖励立即开始累积，无需质押。",
      ja: "USDT か USDC で 1:1 ミント。最低 5 ドル、ミント手数料なし。報酬はすぐ発生し、ステーキングは不要です。",
    },
  },
  {
    id: "transfer",
    icon: "03",
    title: { tr: "Perps cüzdanına aktar", en: "Move to the Perps Wallet", fr: "Passe au Perps Wallet", zh: "转入 Perps 钱包", ja: "Perps ウォレットへ移す" },
    body: {
      tr: "Para önce Cash Wallet'a düşer. İşlem yapmak ve holder puanı kazanmak için Perps Wallet'a aktar. Transfer anlık ve geri alınabilir.",
      en: "Funds land in the Cash Wallet first. Transfer to the Perps Wallet to trade and to earn holder points. The transfer is instant and reversible.",
      fr: "Les fonds arrivent d'abord dans le Cash Wallet. Transfère vers le Perps Wallet pour trader et gagner des holder points. Transfert instantané et réversible.",
      zh: "资金先到 Cash Wallet。转到 Perps Wallet 才能交易并赚取 holder 积分。转账即时且可逆。",
      ja: "資金はまず Cash Wallet に入ります。取引とホルダーポイントのために Perps Wallet へ移します。移動は即時で戻すこともできます。",
    },
  },
  {
    id: "trade",
    icon: "04",
    title: { tr: "İlk işlemi aç", en: "Open your first trade", fr: "Ouvre ton premier trade", zh: "开第一笔交易", ja: "最初の取引を開く" },
    body: {
      tr: "EXECUTE panelinden emir tipi, kaldıraç ve büyüklük seç. TP/SL kur — tetik mark fiyata bakar. Maker ücreti %0,01, taker %0,04.",
      en: "Pick order type, leverage and size in the EXECUTE panel. Set TP/SL — the trigger reads the mark price. Maker fee 0.01%, taker 0.04%.",
      fr: "Choisis type d'ordre, levier et taille dans le panneau EXECUTE. Mets un TP/SL — le déclencheur lit le prix mark. Frais maker 0,01 %, taker 0,04 %.",
      zh: "在 EXECUTE 面板选择订单类型、杠杆和数量。设置 TP/SL —— 触发依据标记价格。Maker 0.01%，Taker 0.04%。",
      ja: "EXECUTE パネルで注文種別・レバレッジ・数量を選びます。TP/SL を設定（トリガーはマーク価格）。メイカー 0.01%、テイカー 0.04%。",
    },
  },
  {
    id: "earn",
    icon: "05",
    title: { tr: "Puan ve getiri topla", en: "Stack points and yield", fr: "Empile points et rendement", zh: "累积积分与收益", ja: "ポイントと利回りを積む" },
    body: {
      tr: "Marjın kendi kendine getiri üretir. Limit emir bırakmak bile maker puanı kazandırır — defterde 3 saniye durması yeter. Holder puanı günde DUSD başına 0,6.",
      en: "Your margin yields on its own. Even resting a limit order earns maker points — 3 seconds on the book is enough. Holder points are 0.6 per DUSD per day.",
      fr: "Ta marge rapporte toute seule. Même un ordre limite au repos gagne des maker points — 3 secondes au carnet suffisent. Holder points : 0,6 par DUSD et par jour.",
      zh: "你的保证金自己生息。哪怕只是挂一个限价单也能赚 Maker 积分 —— 在盘口停留 3 秒即可。Holder 积分为每 DUSD 每天 0.6。",
      ja: "証拠金は自動で利回りを生みます。指値を置くだけでもメイカーポイントが付き、板に 3 秒あれば十分です。ホルダーポイントは 1 DUSD あたり 1 日 0.6。",
    },
  },
  {
    id: "exit",
    icon: "06",
    title: { tr: "Çıkışı planla", en: "Plan the exit", fr: "Planifie la sortie", zh: "规划退出", ja: "出口を計画する" },
    body: {
      tr: "Perps'ten Cash'e aktar, sonra çek. DUSD'yi USDT'ye çevirmek istersen redeem 7 gün kilitli ve %0,1 ücretli; beklemek istemezsen DEX'te swap yap.",
      en: "Transfer Perps to Cash, then withdraw. Turning DUSD back into USDT via redeem means a 7-day lock and a 0.1% fee; swap on a DEX if you would rather not wait.",
      fr: "Transfère de Perps vers Cash, puis retire. Reconvertir le DUSD en USDT par rachat implique un verrou de 7 jours et 0,1 % de frais ; sinon, swap sur un DEX.",
      zh: "先从 Perps 转到 Cash，再提现。通过赎回把 DUSD 换回 USDT 需 7 天锁定并收 0.1% 费用；不想等就在 DEX 上兑换。",
      ja: "Perps から Cash へ移し、それから出金します。リディームで DUSD を USDT に戻す場合は 7 日ロックと 0.1% の手数料。待ちたくなければ DEX でスワップします。",
    },
  },
];

export const LINKS = {
  site: "https://standx.com",
  perps: "https://standx.com/perps",
  docs: "https://docs.standx.com/docs/about-standx",
  sips: "https://docs.standx.com/sip/sip",
  api: "https://docs.standx.com/standx-api/standx-api",
  points: "https://standx.com/point",
  discord: "https://discord.gg/standx",
  x: "https://x.com/StandX_Official",
  builderX: "https://x.com/metacryptox01",
  gallery: "https://gallery.standx.org",
  audits: "https://github.com/standx-labs/stand_audit",
};

export const COMMUNITY = [
  {
    id: "discord",
    href: LINKS.discord,
    tone: "green",
    title: { tr: "Discord", en: "Discord", fr: "Discord", zh: "Discord", ja: "Discord" },
    body: {
      tr: "Her şeyin olduğu yer. Sorular, duyurular, squad'lar ve town hall'lar burada.",
      en: "Where everything happens. Questions, announcements, squads and town halls.",
      fr: "Là où tout se passe. Questions, annonces, squads et town halls.",
      zh: "一切发生的地方。问题、公告、小队和社区会议。",
      ja: "すべてが起きる場所。質問、告知、スクワッド、タウンホール。",
    },
  },
  {
    id: "docs",
    href: LINKS.docs,
    tone: "blue",
    title: { tr: "Dokümanlar", en: "Documentation", fr: "Documentation", zh: "文档", ja: "ドキュメント" },
    body: {
      tr: "61 sayfa: DUSD, perps, kazanç, kaynaklar. Bu sitedeki her rakam oradan geliyor.",
      en: "61 pages: DUSD, perps, earn, resources. Every number on this site comes from there.",
      fr: "61 pages : DUSD, perps, earn, ressources. Chaque chiffre de ce site vient de là.",
      zh: "61 页：DUSD、永续、赚取、资源。本站每个数字都来自那里。",
      ja: "61ページ：DUSD、パープス、Earn、リソース。このサイトの数値はすべてそこ由来です。",
    },
  },
  {
    id: "sips",
    href: LINKS.sips,
    tone: "pink",
    title: { tr: "SIP'ler", en: "The SIPs", fr: "Les SIP", zh: "SIP 提案", ja: "SIP 一覧" },
    body: {
      tr: "SIP-1'den SIP-5C'ye protokolün kendi teklif süreci. Değişikliğin gerekçesi ve şartnamesi.",
      en: "The protocol's own proposal process, SIP-1 through SIP-5C. Motivation and specification for each change.",
      fr: "Le processus de propositions du protocole, de SIP-1 à SIP-5C. Motivation et spécification de chaque changement.",
      zh: "协议自身的提案流程，从 SIP-1 到 SIP-5C。每次变更的动机与规格。",
      ja: "プロトコル自身の提案プロセス、SIP-1 から SIP-5C まで。各変更の動機と仕様。",
    },
  },
  {
    id: "api",
    href: LINKS.api,
    tone: "green",
    title: { tr: "API", en: "API", fr: "API", zh: "API", ja: "API" },
    body: {
      tr: "REST ve WebSocket. Bot yazacaksan JWT, imzalama ve hız limitleri burada.",
      en: "REST and WebSocket. If you are writing a bot, JWT, signing and rate limits are here.",
      fr: "REST et WebSocket. Pour écrire un bot : JWT, signature et limites de débit.",
      zh: "REST 和 WebSocket。要写机器人的话，JWT、签名和限流都在这里。",
      ja: "REST と WebSocket。ボットを書くなら JWT、署名、レート制限はここです。",
    },
  },
  {
    id: "points",
    href: LINKS.points,
    tone: "blue",
    title: { tr: "Puan sayfası", en: "Points page", fr: "Page des points", zh: "积分页面", ja: "ポイントページ" },
    body: {
      tr: "Trader, Maker, Holder ve Referans puanlarının tam dökümü. İki yarılanma tamamlandı.",
      en: "The full breakdown of Trader, Maker, Holder and Referral points. Two halvings are done.",
      fr: "Le détail complet des points Trader, Maker, Holder et Referral. Deux halvings sont passés.",
      zh: "Trader、Maker、Holder 和推荐积分的完整明细。两次减半已完成。",
      ja: "Trader・Maker・Holder・紹介ポイントの内訳。半減は 2 回とも完了しています。",
    },
  },
  {
    id: "audits",
    href: LINKS.audits,
    tone: "pink",
    title: { tr: "Denetimler", en: "Audits", fr: "Audits", zh: "审计", ja: "監査" },
    body: {
      tr: "WatchPug ve RigSec'ten altı rapor, DUSD ve Highway sözleşmeleri için, herkese açık.",
      en: "Six reports from WatchPug and RigSec covering the DUSD and Highway contracts, all public.",
      fr: "Six rapports de WatchPug et RigSec sur les contrats DUSD et Highway, tous publics.",
      zh: "WatchPug 和 RigSec 的六份报告，覆盖 DUSD 与 Highway 合约，全部公开。",
      ja: "WatchPug と RigSec による 6 本のレポート。DUSD と Highway のコントラクトを対象に、すべて公開。",
    },
  },
];
