/**
 * Stander's knowledge base, distilled from docs.standx.com (61 pages, August 2026).
 * Every entry is factual and carries the doc path it came from.
 */
export const DOC_ROOT = "https://docs.standx.com";

export const KNOWLEDGE = [
  {
    id: "what-is-standx",
    source: "/docs/about-standx",
    tags: "standx nedir what is qu'est ce que 什么是 とは perps dex platform protokol protocol universal markets yield genel",
    a: {
      tr: "StandX, BNB Chain ve Solana ana ağında canlı olan yeni nesil bir perps DEX'i. Sloganı \"Universal Markets. Universal Yield.\" Model, stablecoin ile perps'i yan yana koymak değil, çarpmak: DUSD perps'in ürettiği ücret ve funding'den kazanır, perps de getiri taşıyan teminattan sermaye genişliği kazanır. Ekip Binance Futures kurucu kadrosundan ve Goldman Sachs'tan geliyor, tamamen kendi kaynağıyla finanse ediliyor, hiç VC parası almamış.",
      en: "StandX is a next-generation perps DEX live on BNB Chain and Solana mainnet. The tagline is \"Universal Markets. Universal Yield.\" It is Stablecoin × Perps rather than the two bolted together: DUSD earns from the fees and funding that perps generate, while perps gain capital bandwidth from yield-bearing margin. The core team comes from the Binance Futures founding team and Goldman Sachs, and the project is fully self-funded with no VCs.",
      fr: "StandX est un perps DEX de nouvelle génération, en ligne sur BNB Chain et Solana. Son slogan est « Universal Markets. Universal Yield. » C'est Stablecoin × Perps et non les deux collés ensemble : DUSD gagne sur les frais et le funding générés par les perps, et les perps gagnent en capacité de capital grâce à une marge productive. L'équipe vient de l'équipe fondatrice de Binance Futures et de Goldman Sachs, et le projet est entièrement autofinancé, sans VC.",
      zh: "StandX 是新一代永续合约 DEX，已在 BNB Chain 和 Solana 主网上线，口号是「Universal Markets. Universal Yield.」。它是「稳定币 × 永续」而不是两者简单拼接：DUSD 从永续产生的手续费和资金费中获利，永续则从生息保证金中获得资本带宽。核心团队来自币安合约创始团队和高盛，项目完全自筹资金，没有 VC。",
      ja: "StandX は BNB Chain と Solana のメインネットで稼働する次世代パープス DEX です。スローガンは「Universal Markets. Universal Yield.」。ステーブルコインとパープスを並べるのではなく掛け合わせる設計で、DUSD はパープスが生む手数料とファンディングから収益を得て、パープスは利回り付き証拠金から資本の余力を得ます。コアチームは Binance Futures 創設メンバーと Goldman Sachs 出身で、完全自己資金・VC なしです。",
    },
  },
  {
    id: "dusd",
    source: "/docs/dusd-overview",
    tags: "dusd stablecoin teminat collateral margin nedir 稳定币 ステーブル yield bearing getiri",
    a: {
      tr: "DUSD, StandX'in kendi getiri taşıyan stablecoin'i ve tüm platformun fiyatlama ile teminat varlığı. Getiri otomatik olarak cüzdana dağıtılır, ayrıca stake etmen gerekmez. Arkasında piyasa-nötr varlıklar var: riskler tamamen hedge edilir, kaldıraç kullanılmaz, ayrıca bir saklama çözümü ve rezerv fonu bulunur.",
      en: "DUSD is StandX's own yield-bearing stablecoin and the pricing plus margin asset for the whole platform. Yield is auto-distributed straight to your wallet with no staking required. It is backed by market-neutral assets with fully hedged risk and no leverage, plus a custodian solution and a reserve fund.",
      fr: "DUSD est le stablecoin à rendement de StandX, et l'actif de pricing et de marge de toute la plateforme. Le rendement est distribué automatiquement dans ton portefeuille, sans staking. Il est adossé à des actifs neutres au marché, entièrement couverts et sans levier, avec une solution de conservation et un fonds de réserve.",
      zh: "DUSD 是 StandX 自己的生息稳定币，也是整个平台的计价和保证金资产。收益自动分发到钱包，无需质押。它由市场中性资产支撑，风险完全对冲且不使用杠杆，另有托管方案和储备基金。",
      ja: "DUSD は StandX 独自の利回り付きステーブルコインで、プラットフォーム全体の価格建て・証拠金資産です。利回りはウォレットへ自動分配され、ステーキングは不要。マーケットニュートラル資産で裏付けられ、リスクは完全ヘッジ、レバレッジなし。カストディ体制と準備金も備えます。",
    },
  },
  {
    id: "dusd-yield-source",
    source: "/docs/dusd-overview",
    tags: "getiri nereden yield source apy kazanç funding staking gelir revenue 收益 来源 利回り どこから",
    a: {
      tr: "DUSD getirisi iki gerçek kaynaktan gelir: spot varlıkların (ETH, SOL, BNB) stake ödülleri ve short vadeli işlem pozisyonlarının funding ücreti geliri. SIP-3 ile buna üçüncü bir kaynak eklendi: StandX Perps işlem ücretlerinin bir kısmı günlük olarak DUSD getiri havuzuna yönlendiriliyor. Yani yeni token basarak değil, gerçek gelirle ödeniyor.",
      en: "DUSD yield comes from two real sources: staking rewards on spot assets (ETH, SOL, BNB) and funding fee revenue from short futures positions. SIP-3 added a third: a portion of StandX Perps trading fees is routed daily into the DUSD yield pool. It is real yield, not returns manufactured by printing new tokens.",
      fr: "Le rendement DUSD vient de deux sources réelles : les récompenses de staking sur actifs spot (ETH, SOL, BNB) et les revenus de funding des positions futures short. SIP-3 en a ajouté une troisième : une part des frais de trading Perps est routée chaque jour vers le pool de rendement DUSD. C'est du vrai rendement, pas de l'émission de tokens.",
      zh: "DUSD 收益来自两个真实来源：现货资产（ETH、SOL、BNB）的质押奖励，以及空头期货仓位的资金费收入。SIP-3 增加了第三个来源：StandX Perps 交易手续费的一部分每日注入 DUSD 收益池。这是真实收益，不是靠增发代币制造的回报。",
      ja: "DUSD の利回りは二つの実収益から来ます。現物資産（ETH・SOL・BNB）のステーキング報酬と、ショート先物ポジションのファンディング収入です。SIP-3 で三つ目が加わりました：StandX Perps の取引手数料の一部が毎日 DUSD 利回りプールへ流れます。トークン増発ではない実利回りです。",
    },
  },
  {
    id: "mint",
    source: "/docs/dusd-solutions/minting-dusd",
    tags: "mint basmak nasıl alınır satın how to get buy 铸造 ミント usdt usdc minimum 5",
    a: {
      tr: "DUSD'yi StandX sitesinden USDT veya USDC ile bastırırsın, oran 1:1. Minimum tutar 5 USDT/USDC, üst sınır yok. Basımda ücret alınmıyor ve işlem onaylandığı anda neredeyse anında tamamlanıyor. Teminat StandX Vault'a gider, hedge sistemi delta-nötr pozisyonu kurar. Ödüller basımdan hemen sonra işlemeye başlar.",
      en: "You mint DUSD on the StandX site with USDT or USDC at a 1:1 rate. The minimum is $5 USDT/USDC and there is no maximum. There is no minting fee, and it completes almost instantly once the transaction is approved. Collateral goes to the StandX Vault and the hedging system opens the delta-neutral position. Rewards start accruing immediately after minting.",
      fr: "Tu mintes du DUSD sur le site StandX avec de l'USDT ou de l'USDC, au taux 1:1. Le minimum est de 5 USDT/USDC, sans maximum. Aucun frais de mint, et c'est quasi instantané une fois la transaction approuvée. Le collatéral va dans le StandX Vault et le système de couverture ouvre la position delta-neutre. Les récompenses courent immédiatement.",
      zh: "在 StandX 网站用 USDT 或 USDC 以 1:1 铸造 DUSD。最低 5 USDT/USDC，没有上限。铸造不收费，交易批准后几乎即时完成。抵押品进入 StandX Vault，对冲系统建立 delta 中性仓位。铸造后奖励立即开始累积。",
      ja: "DUSD は StandX のサイトで USDT または USDC から 1:1 でミントします。最低 5 USDT/USDC、上限なし。ミント手数料はなく、承認後ほぼ即時に完了します。担保は StandX Vault へ入り、ヘッジシステムがデルタニュートラルのポジションを建てます。報酬はミント直後から発生します。",
    },
  },
  {
    id: "redeem",
    source: "/docs/dusd-solutions/redeeming-dusd",
    tags: "redeem geri bozdurma çıkış withdraw 7 gün lock kilit 赎回 償還 fee 0.1 minimum 10",
    a: {
      tr: "Redeem, DUSD'yi USDT/USDC'ye geri çevirir. Minimum 10 DUSD ve 7 günlük kilit süresi var; bu süre hedge pozisyonlarının kapatılması ve güvenlik için. Redeem ücreti %0,1. İstek gönderildikten sonra iptal edilemez, çünkü pozisyon çözme hemen başlar. Beklemek istemiyorsan PancakeSwap veya Raydium gibi DEX'lerde swap yapabilirsin.",
      en: "Redeeming converts DUSD back into USDT/USDC. The minimum is 10 DUSD and there is a 7-day lock, needed to unwind hedge positions and as a security measure. The redemption fee is 0.1%. Once submitted a request cannot be cancelled, because unwinding starts immediately. If you do not want to wait, swap on a DEX such as PancakeSwap or Raydium instead.",
      fr: "Le rachat reconvertit le DUSD en USDT/USDC. Minimum 10 DUSD et verrou de 7 jours, nécessaire pour déboucler les couvertures et par sécurité. Les frais de rachat sont de 0,1 %. Une demande envoyée ne peut pas être annulée, car le débouclage démarre aussitôt. Sans attendre, tu peux swapper sur un DEX comme PancakeSwap ou Raydium.",
      zh: "赎回把 DUSD 换回 USDT/USDC。最低 10 DUSD，有 7 天锁定期，用于解除对冲仓位并作为安全措施。赎回费为 0.1%。提交后无法取消，因为解仓立即开始。不想等的话，可以在 PancakeSwap 或 Raydium 等 DEX 上兑换。",
      ja: "リディームは DUSD を USDT/USDC に戻します。最低 10 DUSD、7日間のロックがあり、ヘッジ解消とセキュリティのためです。償還手数料は 0.1%。送信後はキャンセルできません（解消が即始まるため）。待ちたくない場合は PancakeSwap や Raydium などの DEX でスワップできます。",
    },
  },
  {
    id: "yield-cycle",
    source: "/docs/dusd-solutions/dusd-yielding-circle",
    tags: "yield cycle döngü 7 gün ödül dağıtım claim takvim calendar eoa 周期 サイクル snapshot",
    a: {
      tr: "Getiri döngüsü 7 gün. Yeni kullanıcıda ilk döngü, DUSD cüzdana girdikten sonraki gün (T+1) başlar; mevcut kullanıcıda eklenen DUSD aynı gün kazanmaya başlar. Ödüller günlük bakiye anlık görüntüleriyle hesaplanır ve 8. günde talep edilebilir hale gelir. Minimum bakiye şartı yok, ama sadece EOA adresleri ödül alabilir. Portfolio sayfasındaki Yield takviminde ay simgeleriyle takip edersin.",
      en: "The yield cycle is 7 days. For a new user the first cycle starts the day after DUSD lands in the wallet (T+1); for an existing holder, added DUSD starts earning the same day. Rewards are calculated from daily balance snapshots and become claimable on day 8. There is no minimum balance, but only EOA addresses can receive rewards. You track it in the Yield calendar on the Portfolio page via the moon icons.",
      fr: "Le cycle de rendement dure 7 jours. Pour un nouvel utilisateur, le premier cycle commence le lendemain de l'arrivée du DUSD (T+1) ; pour un détenteur existant, le DUSD ajouté rapporte le jour même. Les récompenses sont calculées à partir de snapshots quotidiens et deviennent réclamables au jour 8. Aucun solde minimum, mais seules les adresses EOA reçoivent des récompenses. Suivi via le calendrier Yield sur la page Portfolio.",
      zh: "收益周期为 7 天。新用户的第一个周期从 DUSD 进入钱包的次日（T+1）开始；老用户新增的 DUSD 当天即开始计息。奖励按每日余额快照计算，第 8 天可领取。没有最低余额要求，但只有 EOA 地址才能领取奖励。可在 Portfolio 页的 Yield 日历用月亮图标追踪。",
      ja: "利回りサイクルは 7 日です。新規ユーザーは DUSD がウォレットに入った翌日（T+1）から最初のサイクルが始まり、既存保有者は追加分がその日から発生します。報酬は日次残高スナップショットで計算され、8日目に請求可能になります。最低残高はなく、報酬を受け取れるのは EOA アドレスのみです。Portfolio ページの Yield カレンダーの月アイコンで確認できます。",
    },
  },
  {
    id: "wallets",
    source: "/docs/standx-perps-overview/standx-wallet-guide",
    tags: "cash wallet perps wallet cüzdan transfer para nereye 钱包 ウォレット deposit yatırma",
    a: {
      tr: "StandX'te iki cüzdan var. Gelen tüm paralar önce Cash Wallet'a düşer; burası ana hesabın, canlı işlem motorundan ayrı durur. Perps Wallet ise aktif işlem hesabın. Teminat olarak kullanmak veya emir girmek için parayı Cash'ten Perps'e aktarman gerekir. Transfer anlık. Önemli: sadece Perps Wallet'taki DUSD işlem için kullanılır ve sadece o holder puanı kazanır.",
      en: "StandX has two wallets. All incoming funds arrive first in the Cash Wallet, your main account, kept separate from the live trading engine. The Perps Wallet is the active trading account. You must transfer from Cash to Perps before the funds can be used as margin or to place orders, and the transfer is instant. Important: only DUSD in the Perps Wallet can be used for trading, and only that DUSD earns holder points.",
      fr: "StandX a deux portefeuilles. Tous les fonds entrants arrivent d'abord dans le Cash Wallet, ton compte principal, séparé du moteur de trading. Le Perps Wallet est le compte de trading actif. Il faut transférer de Cash vers Perps avant d'utiliser les fonds en marge ou de passer des ordres ; le transfert est instantané. Important : seul le DUSD du Perps Wallet sert au trading et gagne des holder points.",
      zh: "StandX 有两个钱包。所有入金先到 Cash Wallet，这是你的主账户，与实时撮合引擎隔离。Perps Wallet 是活跃交易账户。必须先从 Cash 转到 Perps 才能用作保证金或下单，转账是即时的。重要：只有 Perps Wallet 里的 DUSD 能用于交易，也只有它能赚 holder 积分。",
      ja: "StandX には二つのウォレットがあります。入金はまず Cash Wallet に届きます。これはメイン口座で、取引エンジンとは分離されています。Perps Wallet が実際の取引口座です。証拠金や発注に使うには Cash から Perps へ移す必要があり、移動は即時です。重要：取引に使えるのは Perps Wallet の DUSD だけで、ホルダーポイントもそこでのみ貯まります。",
    },
  },
  {
    id: "trading-fee",
    source: "/docs/standx-perps-solutions/trading-fee",
    tags: "fee ücret komisyon maker taker 0.01 0.04 手续费 手数料 cost maliyet",
    a: {
      tr: "Maker ücreti %0,01, taker ücreti %0,04. Maker deftere likidite ekler (hemen eşleşmeyen limit emir), taker likiditeyi alır (market emri veya anında eşleşen limit). Ücret her eşleşmenin nominal değeri üzerinden hesaplanır. Örnek: 100.000 dolardan 0,2 BTC maker alışta 2 dolar, aynı işlem taker olsaydı 8 dolar.",
      en: "The maker fee is 0.01% and the taker fee is 0.04%. A maker adds liquidity to the book (a limit order that does not match immediately); a taker removes it (a market order or an immediately matched limit). Fees are charged on the notional of each matched trade. Example: buying 0.2 BTC at $100,000 as maker costs $2; the same trade as taker costs $8.",
      fr: "Les frais maker sont de 0,01 % et les frais taker de 0,04 %. Un maker ajoute de la liquidité au carnet (ordre limite non exécuté immédiatement) ; un taker la retire (ordre au marché ou limite exécuté aussitôt). Les frais portent sur le notionnel de chaque exécution. Exemple : acheter 0,2 BTC à 100 000 $ en maker coûte 2 $, en taker 8 $.",
      zh: "Maker 费率 0.01%，Taker 费率 0.04%。Maker 向订单簿提供流动性（未立即成交的限价单），Taker 消耗流动性（市价单或立即成交的限价单）。手续费按每笔成交的名义价值计算。例如：以 100,000 美元买入 0.2 BTC，做 Maker 收 2 美元，做 Taker 收 8 美元。",
      ja: "メイカー手数料は 0.01%、テイカー手数料は 0.04% です。メイカーは板に流動性を置き（即時約定しない指値）、テイカーは流動性を取ります（成行、または即時約定する指値）。手数料は各約定の想定元本に対して発生します。例：10万ドルで 0.2 BTC を買う場合、メイカーなら 2 ドル、テイカーなら 8 ドルです。",
    },
  },
  {
    id: "funding",
    source: "/docs/standx-perps-solutions/funding-rate",
    tags: "funding rate fonlama oranı long short öder pays 资金费率 ファンディング 4% saatlik hourly premium",
    a: {
      tr: "Funding, long ve short pozisyon sahipleri arasındaki doğrudan bir ödemedir — StandX'in aldığı bir ücret değil. Oran pozitifken long'lar short'lara öder, negatifken tersi olur. Amaç perps fiyatını spot'a yapıştırmak. Baz faiz saatte %0,00125 (8 saatte %0,01). Premium endeksi 5 saniyede bir hesaplanır ve zaman ağırlıklı ortalaması alınır. Funding saatte en fazla %4 olabilir.",
      en: "Funding is a payment exchanged directly between longs and shorts — it is not a fee StandX charges. When the rate is positive longs pay shorts; when negative shorts pay longs. Its job is to pin the perp price to spot. The baseline interest rate is 0.00125% per hour (0.01% per 8 hours). The premium index is computed every 5 seconds and time-weighted. Funding is capped at 4% per hour.",
      fr: "Le funding est un paiement direct entre longs et shorts — ce n'est pas un frais prélevé par StandX. Taux positif : les longs paient les shorts ; négatif : l'inverse. Son rôle est d'arrimer le prix du perp au spot. Le taux d'intérêt de base est de 0,00125 % par heure (0,01 % par 8 heures). L'indice de prime est calculé toutes les 5 secondes puis pondéré dans le temps. Le funding est plafonné à 4 % par heure.",
      zh: "资金费是多空双方之间的直接支付 —— 不是 StandX 收取的费用。费率为正时多头付给空头，为负时相反。作用是把永续价格锚定到现货。基准利率为每小时 0.00125%（每 8 小时 0.01%）。溢价指数每 5 秒计算一次并做时间加权。资金费率上限为每小时 4%。",
      ja: "ファンディングはロングとショートの間で直接やり取りされる支払いで、StandX が取る手数料ではありません。プラスならロングがショートに、マイナスならその逆に支払います。目的はパープ価格を現物に近づけることです。基準金利は 1 時間あたり 0.00125%（8 時間で 0.01%）。プレミアム指数は 5 秒ごとに計算され時間加重されます。上限は 1 時間あたり 4% です。",
    },
  },
  {
    id: "mark-price",
    source: "/docs/standx-perps-solutions/price-indicators",
    tags: "mark price işaret fiyat median medyan oracle index 标记价格 マーク価格 manipulation",
    a: {
      tr: "Her pozisyon mark fiyata bağlıdır ve mark fiyat üç girdinin medyanıdır: funding'e göre düzeltilmiş oracle endeksi, son StandX orta fiyatlarının kısa vadeli baz sapması, ve en son gerçekleşen StandX işlemi. Medyan olduğu için tek bir aykırı değer fiyatı çekemez. StandX ayrıca kendi mark fiyatını Binance, OKX ve Bybit ile sürekli karşılaştırır; belirgin sapma olursa geçici olarak onların medyan mark fiyatına sabitler.",
      en: "Every position is anchored to the mark price, which is the median of three inputs: the funding-adjusted oracle index, the short-term basis drift of recent StandX mid prices, and the latest StandX trade. Because it is a median, one outlier cannot drag it away from fair value. StandX also cross-checks its mark against Binance, OKX and Bybit, and temporarily pins to their median mark if it strays noticeably.",
      fr: "Chaque position est ancrée au prix mark, qui est la médiane de trois entrées : l'indice oracle ajusté du funding, la dérive de base à court terme des prix moyens StandX récents, et le dernier trade StandX. Étant une médiane, une valeur aberrante ne peut pas l'éloigner de la juste valeur. StandX compare aussi en continu à Binance, OKX et Bybit, et s'aligne temporairement sur leur mark médian en cas d'écart notable.",
      zh: "每个仓位都锚定标记价格，它是三个输入的中位数：经资金费调整的预言机指数、近期 StandX 中间价的短期基差漂移，以及最新的 StandX 成交价。由于取中位数，单个异常值无法拉偏公允价值。StandX 还持续与币安、OKX、Bybit 交叉校验，偏离明显时临时锚定到它们的中位标记价。",
      ja: "すべてのポジションはマーク価格に紐づきます。マーク価格は三つの入力の中央値です：ファンディング調整済みオラクル指数、直近 StandX 仲値の短期ベーシス、そして直近の StandX 約定価格。中央値なので外れ値ひとつでは公正価値から動きません。さらに Binance・OKX・Bybit と常時照合し、大きく乖離した場合は一時的にそれらの中央マーク価格に固定します。",
    },
  },
  {
    id: "liquidation",
    source: "/docs/standx-perps-solutions/liquidation",
    tags: "liquidation likidasyon tasfiye margin call bankruptcy 1.25 清算 リクイデーション ioc",
    a: {
      tr: "Likidasyon, marj bakiyesi sürdürme marjını karşılayamadığında tetiklenir ve son işlem fiyatına değil mark fiyata bakar. Küçük pozisyonlar (Tier 1 ve altı) tamamen iflas fiyatından IOC emir olarak gönderilir. Dolmazsa kalan pozisyonu vault devralır; vault kapasitesi dolarsa ADL devreye girer. Büyük pozisyonlar en üst dilimden başlayarak kademeli kapatılır ve marj toparlanırsa işlem hemen durur. Likidasyon temizleme ücreti nominal değerin %1,25'i, ama pozisyon iflas etmişse ücret alınmaz.",
      en: "Liquidation triggers when the margin balance can no longer meet the maintenance margin, and it reads the mark price rather than the last trade. Small positions (Tier 1 and below) are sent whole as an IOC order at the bankruptcy price. If that does not fill, the vault takes over the remainder; if vault capacity is reached, ADL fires. Large positions are liquidated tier by tier from the top tranche and stop immediately if margin recovers. The clearance fee is 1.25% of notional, and nothing is charged if the position is bankrupt.",
      fr: "La liquidation se déclenche quand la marge ne couvre plus la marge de maintenance, et elle se base sur le prix mark, pas sur le dernier prix traité. Les petites positions (Tier 1 et en dessous) partent en entier en ordre IOC au prix de faillite. Si ça ne remplit pas, le vault reprend le reste ; si la capacité du vault est atteinte, l'ADL se déclenche. Les grosses positions sont liquidées par tranches en partant du haut et s'arrêtent dès que la marge se rétablit. Les frais de liquidation sont de 1,25 % du notionnel, et rien n'est prélevé si la position est en faillite.",
      zh: "当保证金余额无法满足维持保证金时触发清算，依据的是标记价格而非最新成交价。小仓位（Tier 1 及以下）以破产价整单以 IOC 方式发出。若未完全成交，剩余部分由金库接管；金库容量耗尽则触发 ADL。大仓位从最高档开始分档清算，保证金恢复后立即停止。清算清偿费为名义价值的 1.25%，若仓位已破产则不收费。",
      ja: "清算は証拠金残高が維持証拠金を満たせなくなった時に発動し、直近約定ではなくマーク価格を参照します。小口ポジション（Tier 1 以下）は破産価格の IOC 注文として全量出されます。約定しきらない場合は残りを Vault が引き受け、Vault の容量が尽きると ADL が発動します。大口はティアごとに上から段階的に処理され、証拠金が回復すれば即座に停止します。清算手数料は想定元本の 1.25%、破産状態なら請求されません。",
    },
  },
  {
    id: "adl",
    source: "/docs/standx-perps-solutions/adl",
    tags: "adl auto deleveraging otomatik kaldıraç azaltma 自动减仓 自動デレバレッジ son çare",
    a: {
      tr: "ADL (Auto-Deleveraging), aşırı piyasa koşullarında platformun ödeme gücünü korumak için kârlı işlemcilerin pozisyonlarını otomatik olarak azaltır. Sadece son çare olarak devreye girer: önce likide edilen pozisyonlar defterden geçirilir, sonra kalanı platformun vault'u emer, ikisi de tükenirse ADL çalışır. Seçim kaldıraç ve gerçekleşmemiş kâra göre sıralanır; en yüksek risk-ayarlı getirisi olanlar önce seçilir.",
      en: "ADL (Auto-Deleveraging) automatically reduces profitable traders' positions in extreme conditions so the platform stays solvent. It is a last resort: liquidated positions go through the order book first, then the platform vault absorbs what is left, and only when both are exhausted does ADL fire. Traders are ranked by leverage and unrealized PnL, so the highest risk-adjusted returns are picked first.",
      fr: "L'ADL (Auto-Deleveraging) réduit automatiquement les positions des traders profitables en conditions extrêmes pour garder la plateforme solvable. C'est un dernier recours : les positions liquidées passent d'abord par le carnet, puis le vault absorbe le reste, et l'ADL ne se déclenche que si les deux sont épuisés. Le classement se fait sur le levier et le PnL non réalisé ; les meilleurs rendements ajustés du risque sont pris en premier.",
      zh: "ADL（自动减仓）在极端行情下自动减少盈利交易者的仓位，以保证平台偿付能力。它是最后手段：清算仓位先走订单簿，剩余部分由平台金库承接，只有两者都耗尽才触发 ADL。排序依据是杠杆和未实现盈亏，风险调整后收益最高的会被优先选中。",
      ja: "ADL（自動デレバレッジ）は極端な相場でプラットフォームの支払能力を守るため、利益の出ているトレーダーのポジションを自動的に縮小します。最後の手段です：清算ポジションはまず板を通り、残りをプラットフォーム Vault が吸収し、両方が尽きた時のみ ADL が動きます。レバレッジと含み益で順位付けされ、リスク調整後リターンが高い順に選ばれます。",
    },
  },
  {
    id: "margin-leverage",
    source: "/docs/standx-perps-solutions/margin-leverage",
    tags: "margin leverage kaldıraç marj cross isolated tier dilim 保证金 杠杆 レバレッジ 40x maintenance",
    a: {
      tr: "Başlangıç marjı pozisyon değerinin teminat olarak ayrılan kısmıdır; %2 başlangıç marjı 50x kaldıraç demektir. Sürdürme marjı pozisyonu açık tutmak için gereken minimumdur ve pozisyon büyüdükçe artar. Cross modda tüm bakiye pozisyonlar arasında paylaşılır, isolated modda her pozisyonun kendi marjı vardır ve zarar o marjla sınırlıdır. Dilimler: 0–1M USDT'de 40x ve %1,25 sürdürme; 1–10M'de 20x ve %2,50; 10–100M'de 10x ve %5; 100–500M'de 5x ve %10.",
      en: "Initial margin is the share of position value posted as collateral; 2% initial margin means 50x leverage. Maintenance margin is the minimum needed to keep the position open and rises with position size. In cross mode the whole balance is shared across positions; in isolated mode each position has its own margin and losses are capped there. Tiers: 0–1M USDT at 40x and 1.25% maintenance; 1–10M at 20x and 2.50%; 10–100M at 10x and 5%; 100–500M at 5x and 10%.",
      fr: "La marge initiale est la part de la valeur de position déposée en collatéral ; 2 % de marge initiale = 50x de levier. La marge de maintenance est le minimum pour garder la position ouverte et augmente avec la taille. En mode cross, tout le solde est partagé entre les positions ; en isolated, chaque position a sa marge et les pertes y sont plafonnées. Paliers : 0–1M USDT à 40x et 1,25 % ; 1–10M à 20x et 2,50 % ; 10–100M à 10x et 5 % ; 100–500M à 5x et 10 %.",
      zh: "初始保证金是作为抵押的仓位价值比例；2% 初始保证金即 50 倍杠杆。维持保证金是保持仓位所需的最低水平，随仓位规模递增。全仓模式下全部余额在各仓位间共享；逐仓模式下每个仓位有独立保证金，亏损以此为上限。档位：0–100 万 USDT 为 40 倍、维持 1.25%；100–1000 万为 20 倍、2.50%；1000 万–1 亿为 10 倍、5%；1–5 亿为 5 倍、10%。",
      ja: "当初証拠金はポジション価値のうち担保として差し入れる割合で、2% なら 50 倍レバレッジです。維持証拠金はポジションを維持するための最低水準で、サイズが大きいほど上がります。クロスでは残高全体を各ポジションで共有し、分離では各ポジションが独自の証拠金を持ち損失もそこまでです。ティア：0–100万 USDT は 40 倍・維持 1.25%、100–1000万は 20 倍・2.50%、1000万–1億は 10 倍・5%、1–5億は 5 倍・10%。",
    },
  },
  {
    id: "tp-sl",
    source: "/docs/standx-perps-solutions/take-profit-and-stop-loss-orders-tp-sl",
    tags: "tp sl take profit stop loss kar al zarar durdur oco 止盈 止损 利確 損切り 10 limit",
    a: {
      tr: "TP/SL, belirlediğin fiyata ulaşıldığında otomatik kapanış emri gönderen tetikleyici emirlerdir ve tetik her zaman mark fiyata bakar. Her işlem çifti için en fazla 10 aktif TP/SL olabilir. Emir seviyesindeki TP ve SL bir OCO çiftidir: biri dolunca diğeri otomatik iptal olur. Kısmi kapanışlar (örneğin %10 ve %20) birbirinden bağımsız yaşar. Dikkat: fiyat tetik seviyesini zaten geçtiyse emir tetiklenmez, ayrıca marj yetersizse kapanış emri oluşturulamaz.",
      en: "TP/SL are trigger orders that submit a closing order when your set price is reached, and the trigger always reads the mark price. Each trading pair allows at most 10 active TP/SL orders. Order-level TP and SL form an OCO pair: when one fills, the other is cancelled automatically. Partial closes (say 10% and 20%) coexist independently. Watch out: if price has already passed the trigger level it will not fire, and if margin is insufficient the closing order cannot be created.",
      fr: "Les TP/SL sont des ordres déclencheurs qui envoient un ordre de clôture au prix défini, et le déclencheur lit toujours le prix mark. Chaque paire autorise au maximum 10 TP/SL actifs. Les TP et SL au niveau de l'ordre forment une paire OCO : quand l'un s'exécute, l'autre est annulé. Les clôtures partielles (10 %, 20 %) coexistent indépendamment. Attention : si le prix a déjà dépassé le niveau, l'ordre ne se déclenche pas, et si la marge est insuffisante l'ordre de clôture ne peut pas être créé.",
      zh: "TP/SL 是触发单，价格达到设定水平时提交平仓单，触发始终依据标记价格。每个交易对最多 10 个有效 TP/SL。订单级 TP 和 SL 构成 OCO 组合：一个成交，另一个自动取消。部分平仓（如 10%、20%）彼此独立共存。注意：如果价格已经越过触发价则不会触发；保证金不足时也无法创建平仓单。",
      ja: "TP/SL は設定価格に到達すると決済注文を出すトリガー注文で、トリガーは常にマーク価格を参照します。1銘柄あたり有効な TP/SL は最大 10 件です。注文レベルの TP と SL は OCO ペアで、片方が約定するともう片方は自動キャンセルされます。部分決済（10%、20% など）は独立して共存します。注意：価格がすでにトリガー水準を通過していると発動せず、証拠金不足だと決済注文を作成できません。",
    },
  },
  {
    id: "points",
    source: "/docs/standx-earn/mainnet-campaigns",
    tags: "points puan holder maker trader kazanmak earn 积分 ポイント 0.6 3 seconds limit order",
    a: {
      tr: "Üç puan türü var. Holder puanı: günde DUSD başına 0,6 puan, ama DUSD'nin Perps Wallet'ta veya Vault'ta olması şart — Cash Wallet sayılmaz. Maker puanı: StandX, hiç gerçekleşmeyen limit emirlere puan veren ilk perps DEX'i; emrin defterde 3 saniyeden uzun durması yeterli, yani sıfır işlem riskiyle puan kazanılır. Çarpan mark fiyata yakınlıkla doğrusal artar: 0–10 bps arası %100'den %40'a, 10–30 bps arası %40'tan %12,5'e, 30–100 bps arası %12,5'ten sıfıra. Ayrıca Loser puanı var: 1 dolar gerçekleşmiş zarara 5 puan.",
      en: "There are three point types. Holder points: 0.6 per DUSD per day, but the DUSD must sit in the Perps Wallet or a Vault — the Cash Wallet does not count. Maker points: StandX is the first perps DEX to award points for limit orders that never execute; the order only has to rest on the book for over 3 seconds, so points can be earned with zero trading risk. The multiplier scales linearly with closeness to mark: 100% → 40% across 0–10 bps, 40% → 12.5% across 10–30 bps, 12.5% → 0 across 30–100 bps. There are also Loser points: 5 points per $1 of realised losses.",
      fr: "Il y a trois types de points. Holder : 0,6 par DUSD et par jour, mais le DUSD doit être dans le Perps Wallet ou un Vault — le Cash Wallet ne compte pas. Maker : StandX est le premier perps DEX à récompenser des ordres limites jamais exécutés ; il suffit que l'ordre reste au carnet plus de 3 secondes, donc des points sans risque de trading. Le multiplicateur croît linéairement avec la proximité du mark : 100 % → 40 % sur 0–10 bps, 40 % → 12,5 % sur 10–30 bps, 12,5 % → 0 sur 30–100 bps. Il existe aussi les Loser points : 5 points par dollar de pertes réalisées.",
      zh: "共有三类积分。Holder 积分：每 DUSD 每天 0.6 分，但 DUSD 必须在 Perps Wallet 或 Vault 中 —— Cash Wallet 不算。Maker 积分：StandX 是首个为未成交限价单发放积分的永续 DEX，订单只要在盘口停留超过 3 秒即可，等于零交易风险赚积分。乘数随靠近标记价线性上升：0–10 bps 从 100% 到 40%，10–30 bps 从 40% 到 12.5%，30–100 bps 从 12.5% 到 0。还有 Loser 积分：每 1 美元已实现亏损得 5 分。",
      ja: "ポイントは三種類。ホルダーポイントは 1 DUSD あたり 1 日 0.6 ポイントですが、DUSD は Perps Wallet か Vault にある必要があります（Cash Wallet は対象外）。メイカーポイントは、約定しない指値注文にポイントを与える初のパープス DEX という仕組みで、板に 3 秒以上置くだけで取引リスクゼロで貯まります。倍率はマーク価格への近さに比例し、0–10 bps で 100%→40%、10–30 bps で 40%→12.5%、30–100 bps で 12.5%→0 と変化します。さらに Loser ポイントもあり、実現損失 1 ドルにつき 5 ポイントです。",
    },
  },
  {
    id: "halving",
    source: "/docs/standx-earn/mainnet-campaigns",
    tags: "halving yarılanma puan azaldı point emission 减半 半減 may august 2026",
    a: {
      tr: "StandX iki Puan Yarılanması tamamladı; her biri Trader, Maker ve Holder puan üretim hızını yarıya indirdi. Birincisi 24 Mayıs 2026 saat 00:00 GMT, ikincisi ve sonuncusu 10 Ağustos 2026 saat 08:00 GMT'de oldu. Başka yarılanma olmayacak. Maker Uptime Programı yarılanmadan etkilenmedi: yakınlık ağırlığı ve Maker Saatleri aynı kaldı. Gerekçe, platformdaki DUSD büyürken emisyonu sürdürülebilir tutmak ve daha önce kazanılmış puanların değerini korumak.",
      en: "StandX has completed two Point Halvings, each cutting Trader, Maker and Holder point emission rates to half. The first was 24 May 2026 at 00:00 GMT; the second and final one was 10 August 2026 at 08:00 GMT. No further halvings will take place. The Maker Uptime Program was not affected: proximity weighting and Maker Hours stayed the same. The rationale is keeping emissions sustainable as DUSD on the platform grows, while preserving the value of points already earned.",
      fr: "StandX a réalisé deux Point Halvings, chacun divisant par deux l'émission de points Trader, Maker et Holder. Le premier le 24 mai 2026 à 00:00 GMT ; le second et dernier le 10 août 2026 à 08:00 GMT. Il n'y en aura pas d'autre. Le Maker Uptime Program n'a pas été touché : la pondération de proximité et les Maker Hours restent identiques. L'objectif est de garder l'émission soutenable à mesure que le DUSD croît, tout en préservant la valeur des points déjà acquis.",
      zh: "StandX 已完成两次积分减半，每次将 Trader、Maker、Holder 积分发放速率降为一半。第一次是 2026 年 5 月 24 日 00:00 GMT，第二次也是最后一次为 2026 年 8 月 10 日 08:00 GMT，此后不再减半。Maker Uptime 计划不受影响：邻近权重和 Maker Hours 保持不变。原因是在平台 DUSD 增长的同时保持积分发放可持续，并保护此前已获得积分的价值。",
      ja: "StandX はポイント半減を 2 回実施し、Trader・Maker・Holder のポイント発行率をそれぞれ半分にしました。1 回目は 2026 年 5 月 24 日 00:00 GMT、2 回目かつ最後は 2026 年 8 月 10 日 08:00 GMT です。今後の半減はありません。Maker Uptime プログラムは影響を受けず、近接ウェイトと Maker Hours はそのままです。狙いは、プラットフォーム上の DUSD が増える中で発行を持続可能に保ち、既存ポイントの価値を守ることです。",
    },
  },
  {
    id: "network-yield",
    source: "/docs/standx-perps-solutions/network-yield",
    tags: "referral davet network yield komisyon rebate 20% 500000 邀请 返佣 紹介 リファラル",
    a: {
      tr: "Network Yield, StandX'in davet programı: davet ettiklerinin işlem ücretlerinin %20'sine kadarını kazanırsın, bir kısmını da onlara iade edebilirsin. Varsayılan olarak açık değil — %5'lik taban oranı açmak için kişisel kümülatif işlem hacminin 500.000 DUSD'ye ulaşması gerekir ve tüm geçmiş hacmin sayılır. Üst basamaklar Network Hacmiyle gelir: 2,5M'de %10, 7,5M'de %15, 15M'de %20. Ayrıca hem davet edene hem edilene tüm puan türlerinde %5 bonus verilir.",
      en: "Network Yield is StandX's referral program: you earn up to 20% of your invitees' trading fees and can pass part of it back to them. It is not on by default — you need 500,000 DUSD of cumulative personal trading volume to unlock the 5% base rate, and your entire history counts. Higher tiers come from Network Volume: 10% at 2.5M, 15% at 7.5M, 20% at 15M. It also gives both referrer and invitee a +5% bonus on every point type.",
      fr: "Network Yield est le programme de parrainage de StandX : tu gagnes jusqu'à 20 % des frais de trading de tes invités et peux leur en reverser une partie. Il n'est pas actif par défaut — il faut 500 000 DUSD de volume personnel cumulé pour débloquer le taux de base de 5 %, et tout ton historique compte. Les paliers supérieurs viennent du Network Volume : 10 % à 2,5M, 15 % à 7,5M, 20 % à 15M. Il donne aussi +5 % de bonus de points au parrain comme au filleul.",
      zh: "Network Yield 是 StandX 的推荐计划：你可赚取被邀请人交易手续费的最高 20%，并可返还一部分给他们。默认未开启 —— 个人累计交易量需达到 500,000 DUSD 才解锁 5% 基础比例，且全部历史交易量都计入。更高档位由 Network Volume 决定：250 万为 10%，750 万为 15%，1500 万为 20%。此外推荐人和被推荐人在所有积分类型上都有 +5% 加成。",
      ja: "Network Yield は StandX の紹介プログラムです。招待した人の取引手数料の最大 20% を得られ、その一部を相手に還元できます。既定では無効で、5% の基本レートを解放するには個人の累計取引高が 500,000 DUSD に達する必要があり、過去すべての履歴が算入されます。上位ティアは Network Volume で決まり、250万で 10%、750万で 15%、1500万で 20% です。さらに紹介者・被紹介者ともに全ポイント種別で +5% ボーナスが付きます。",
    },
  },
  {
    id: "vault-slp",
    source: "/docs/standx-perps-overview/standx-vault-slp",
    tags: "vault slp liquidity provider kasa t+4 nav tvl 金库 ボールト deposit",
    a: {
      tr: "StandX Liquidity Provider (SLP), Perps borsasını besleyen sistem seviyesinde bir vault. Getirisi market yapıcılık stratejileri, likidasyonların gerçekleştirilmesi ve platform işlem ücretlerinin bir payından gelir. Protokol vault'u olduğu için kârdan pay almaz, net getirinin tamamı sağlayıcılara dağıtılır. Yatıranlar TVL'deki payını temsil eden SLP token alır; SLP fiyatı = Vault TVL / Toplam SLP arzı. Yatırımlar T+4'te işleme girer, çekimler boşta fon varsa anında, yoksa en fazla T+4'te tamamlanır.",
      en: "The StandX Liquidity Provider (SLP) is a system-level vault powering the Perps exchange. Returns come from market-making strategies, performing liquidations, and a share of platform trading fees. As a protocol vault it takes no cut of profits — all net returns are distributed to providers. Depositors receive SLP tokens representing a share of TVL; SLP price = Vault TVL / total SLP supply. Deposits settle after T+4, and withdrawals are instant if idle funds exist, otherwise up to T+4.",
      fr: "Le StandX Liquidity Provider (SLP) est un vault au niveau système qui alimente l'exchange Perps. Les rendements viennent des stratégies de market making, de l'exécution des liquidations et d'une part des frais de trading. En tant que vault de protocole, il ne prend aucune commission : tous les rendements nets vont aux fournisseurs. Les déposants reçoivent des tokens SLP représentant une part du TVL ; prix SLP = TVL du vault / offre totale de SLP. Les dépôts sont actifs après T+4 ; les retraits sont instantanés s'il y a des fonds inactifs, sinon jusqu'à T+4.",
      zh: "StandX Liquidity Provider（SLP）是驱动 Perps 交易所的系统级金库。收益来自做市策略、执行清算，以及平台交易手续费的分成。作为协议金库，它不抽取利润分成，全部净收益分配给流动性提供者。存入者获得代表 TVL 份额的 SLP 代币；SLP 价格 = 金库 TVL / SLP 总供应量。存款在 T+4 后生效；若金库有闲置资金则提现即时到账，否则最多 T+4。",
      ja: "StandX Liquidity Provider（SLP）は Perps 取引所を支えるシステムレベルの Vault です。リターンはマーケットメイク戦略、清算の執行、プラットフォーム取引手数料の一部から生まれます。プロトコル Vault なので利益från分配を取らず、純収益はすべて提供者へ配分されます。預入者は TVL の持分を表す SLP トークンを受け取り、SLP 価格 = Vault TVL ÷ SLP 総供給量です。入金は T+4 で稼働し、出金は余剰資金があれば即時、なければ最大 T+4 です。",
    },
  },
  {
    id: "community-vaults",
    source: "/sip/sip-5b-community-vault",
    tags: "community vault sip-5b strategy reward shield topluluk kasası 100 dusd 5% owner 社区金库",
    a: {
      tr: "Community Vaults, SIP-5B ile gelen kullanıcı vault'ları ve Universal Markets'ın sermaye katmanı. Üç tür var ve tür kuruluşta seçilir, sonra değişmez: Strategy (yatıranlar bir yöneticiye sermaye verir, şu an canlı), Reward (bir çiftin maker teşvik bütçesi) ve Shield (ADL'den önce likidasyonları emen sigorta sermayesi). Kurulum ücreti 100 DUSD ve iade edilmez. Kâr payı %5, %10, %15, %20 veya %25 seçilebilir. Sahibin her zaman vault'un en az %5'ini tutması gerekir. Çekimler kilit süresinden sonra normal koşullarda 4 gün içinde işlenir.",
      en: "Community Vaults arrived with SIP-5B and are the capital layer of Universal Markets. There are three types, fixed at creation: Strategy (depositors fund an owner who trades, live today), Reward (a pair's maker incentive budget) and Shield (insurance capital that absorbs liquidations ahead of ADL). The creation fee is 100 DUSD and is non-refundable. Profit share options are 5%, 10%, 15%, 20% or 25%. The owner must always hold at least 5% of the vault. Withdrawals are processed within 4 days after the lock period under normal conditions.",
      fr: "Les Community Vaults sont arrivés avec SIP-5B et forment la couche de capital des Universal Markets. Trois types, fixés à la création : Strategy (les déposants financent un gérant qui trade, déjà en ligne), Reward (le budget d'incitation maker d'une paire) et Shield (capital d'assurance qui absorbe les liquidations avant l'ADL). Les frais de création sont de 100 DUSD, non remboursables. Le partage de profit est de 5, 10, 15, 20 ou 25 %. Le propriétaire doit toujours détenir au moins 5 % du vault. Les retraits sont traités sous 4 jours après la période de blocage.",
      zh: "Community Vaults 随 SIP-5B 推出，是 Universal Markets 的资本层。共三种类型，创建时确定且不可更改：Strategy（存款人把资金交给操盘者，目前已上线）、Reward（某交易对的做市激励预算）和 Shield（在 ADL 之前吸收清算的保险资本）。创建费为 100 DUSD，不可退还。利润分成可选 5%、10%、15%、20% 或 25%。所有者必须始终持有金库至少 5%。正常情况下，锁定期结束后提现在 4 天内处理。",
      ja: "Community Vaults は SIP-5B で導入され、Universal Markets の資本レイヤーです。種類は三つで作成時に固定されます：Strategy（預入者が運用者に資金を託す。現在稼働中）、Reward（銘柄のメイカー報酬予算）、Shield（ADL の前に清算を吸収する保険資本）。作成手数料は 100 DUSD で返金不可。利益シェアは 5%・10%・15%・20%・25% から選べます。オーナーは常に Vault の 5% 以上を保有する必要があります。出金はロック期間後、通常時 4 日以内に処理されます。",
    },
  },
  {
    id: "sip-1",
    source: "/sip/sip-1-block-trade",
    tags: "sip-1 sip1 block trade blok işlem otc büyük emir 25 counterparties 大宗交易 ブロック取引",
    a: {
      tr: "SIP-1 Block Trade, büyük emirleri açık defteri süpürmeden eşe-eş anlaşmayla yapmanı sağlar; her adım zincire yazılır. Piyasa etkisi sıfırdır: Block Trade fiyatları mark fiyatı, son işlem fiyatını, mumları, funding'i ve likidasyon tetiklerini etkilemez. Tek bir blok en fazla 25 karşı tarafı destekler. İki mod var: Flexible (eşleşme geldikçe hemen kapanır, taker iptal edemez) ve FullMatch (blok %100 dolmadan kapanış olmaz, taker iptal edebilir). Durum: Implemented.",
      en: "SIP-1 Block Trade lets you negotiate large trades peer-to-peer without sweeping the public book, with every step recorded on-chain. Market impact is zero: block prices do not touch mark price, last trade price, candles, funding, or liquidation triggers. A single block supports up to 25 counterparties. Two modes exist: Flexible (settles as matches arrive, takers cannot cancel) and FullMatch (nothing settles until the block is 100% filled, takers can cancel). Status: Implemented.",
      fr: "SIP-1 Block Trade permet de négocier de gros trades en pair-à-pair sans balayer le carnet public, chaque étape étant inscrite on-chain. L'impact marché est nul : les prix de bloc n'affectent ni le mark, ni le dernier prix, ni les bougies, ni le funding, ni les déclencheurs de liquidation. Un bloc supporte jusqu'à 25 contreparties. Deux modes : Flexible (règlement au fil des matchs, le taker ne peut pas annuler) et FullMatch (aucun règlement avant 100 % de remplissage, le taker peut annuler). Statut : Implemented.",
      zh: "SIP-1 大宗交易让你在不扫公开订单簿的情况下点对点协商大额成交，每一步都上链记录。市场冲击为零：大宗价格不影响标记价格、最新成交价、K 线、资金费率或清算触发。单个区块最多支持 25 个对手方。两种模式：Flexible（有匹配即结算，taker 不能取消）和 FullMatch（未 100% 撮合前不结算，taker 可取消）。状态：已实施。",
      ja: "SIP-1 ブロック取引は、公開板を掃かずに大口をピアツーピアで交渉でき、すべての手順がオンチェーンに記録されます。マーケットインパクトはゼロで、ブロック価格はマーク価格・直近約定価格・ローソク足・ファンディング・清算トリガーに影響しません。1 ブロックあたり最大 25 の対戦相手に対応します。モードは二つ：Flexible（マッチごとに即決済、テイカーはキャンセル不可）と FullMatch（100% 約定まで決済なし、テイカーはキャンセル可）。ステータス：実装済み。",
    },
  },
  {
    id: "sip-2",
    source: "/sip/sip-2-position-yield",
    tags: "sip-2 sip2 position yield pozisyon getirisi fee share açık pozisyon 仓位收益 ポジション利回り",
    a: {
      tr: "SIP-2 Position Yield, uygun protokol ücret akışının ayarlanabilir bir kısmını açık kalan pozisyonlara dağıtan bir mekanizma. Ücret katılımını tek tek işlem anlarından zaman-nitelikli pozisyon katılımına taşır; icra, funding, marj ve likidasyon mantığını değiştirmez. Pozisyon hangi yolla açıldığı fark etmez — defter, market emri, limit emir veya Block Trade eşit muamele görür. Sert bir kural var: bir pozisyon getiri biriktirmeden önce en az bir tam funding döngüsünü tamamlamalıdır. Varsayılan dağıtım günlük. Durum: Implemented.",
      en: "SIP-2 Position Yield routes a configurable share of eligible protocol fee flow to positions that stay open. It moves fee participation from discrete execution events to time-qualified position participation without changing execution, funding, margining or liquidation semantics. The opening path does not matter — order book, market order, limit order and Block Trade are all treated equally. One hard rule: a position must live through at least one complete funding settlement cycle before it can accrue yield. Default settlement is daily. Status: Implemented.",
      fr: "SIP-2 Position Yield alloue une part configurable du flux de frais éligibles aux positions qui restent ouvertes. Il déplace la participation aux frais des événements d'exécution ponctuels vers une participation qualifiée dans le temps, sans changer l'exécution, le funding, la marge ni la liquidation. Le chemin d'ouverture est neutre : carnet, ordre au marché, ordre limite et Block Trade sont traités pareillement. Règle stricte : une position doit traverser au moins un cycle complet de funding avant d'accumuler du rendement. Règlement quotidien par défaut. Statut : Implemented.",
      zh: "SIP-2 仓位收益把可分配协议手续费流的一部分按配置分给持续持仓的仓位。它把手续费参与从单次成交事件转向按时间资格的持仓参与，同时不改变撮合、资金费、保证金或清算逻辑。开仓路径无差别 —— 订单簿、市价单、限价单和大宗交易一视同仁。一条硬规则：仓位必须完整经历至少一个资金费结算周期后才能累积收益。默认每日结算。状态：已实施。",
      ja: "SIP-2 ポジション利回りは、対象となるプロトコル手数料フローの設定可能な割合を、保有され続けるポジションへ配分します。手数料への参加を単発の約定イベントから、時間条件を満たしたポジション参加へ移す仕組みで、約定・ファンディング・証拠金・清算の挙動は変えません。建て方は中立で、板・成行・指値・ブロック取引を同等に扱います。厳格な条件が一つ：利回りが付く前に、最低 1 回の完全なファンディング決済サイクルを経る必要があります。既定の決済は日次。ステータス：実装済み。",
    },
  },
  {
    id: "sip-3",
    source: "/sip/sip-3-dusd-native-yield",
    tags: "sip-3 sip3 dusd native yield expansion ücret yönlendirme fee routing 原生收益 ネイティブ利回り",
    a: {
      tr: "SIP-3 DUSD Native Yield Expansion, StandX Perps işlem ücretlerinin bir kısmını DUSD getiri havuzuna yönlendirir. Yönlendirilen tutar net işlem ücreti gelirinden (referans iadeleri ve ortaklık ödemeleri sonrası) alınır ve günlük olarak DUSD Settlement Pool'a akar. Getiri artışı tüm DUSD sahiplerine gider: zincirde tutana da, PancakeSwap/Raydium'da likidite verene de, Perps cüzdanında bekletene de. SIP-2 tahsisinden bağımsız muhasebeleşir. Ayrıca isteğe bağlı bir Yield Smoothing Reserve, yoğun dönemlerin fazlasını sakin dönemlerde APY'yi desteklemek için tutar. Durum: Implemented.",
      en: "SIP-3 DUSD Native Yield Expansion routes a portion of StandX Perps trading fees into the DUSD yield pool. The routed amount comes from net trading fee revenue (after referral rebates and affiliate payouts) and flows daily into the DUSD Settlement Pool. The boost reaches every DUSD holder: on-chain wallets, LPs on PancakeSwap/Raydium, and unutilized DUSD in the Perps wallet. It is accounted for separately from the SIP-2 allocation. An optional Yield Smoothing Reserve buffers surplus from high-volume periods to support APY in quiet ones. Status: Implemented.",
      fr: "SIP-3 DUSD Native Yield Expansion route une partie des frais de trading Perps vers le pool de rendement DUSD. Le montant vient du revenu net de frais (après rabais de parrainage et paiements d'affiliation) et alimente quotidiennement le DUSD Settlement Pool. Le gain touche tous les détenteurs de DUSD : portefeuilles on-chain, LP sur PancakeSwap/Raydium, et DUSD inutilisé dans le Perps wallet. La comptabilité est séparée de l'allocation SIP-2. Une Yield Smoothing Reserve optionnelle met en réserve le surplus des périodes actives pour soutenir l'APY dans les périodes calmes. Statut : Implemented.",
      zh: "SIP-3 DUSD 原生收益扩展把 StandX Perps 交易手续费的一部分导入 DUSD 收益池。导入金额取自净交易手续费收入（扣除推荐返佣和联盟支出后），每日流入 DUSD Settlement Pool。收益提升覆盖所有 DUSD 持有者：链上钱包、PancakeSwap/Raydium 的 LP，以及 Perps 钱包中闲置的 DUSD。其会计与 SIP-2 分配相互独立。另有可选的 Yield Smoothing Reserve，把高交易量时期的盈余缓冲起来，用于清淡时期支撑 APY。状态：已实施。",
      ja: "SIP-3 DUSD ネイティブ利回り拡張は、StandX Perps の取引手数料の一部を DUSD 利回りプールへ回します。原資は純取引手数料収益（紹介リベートとアフィリエイト支払い後）で、毎日 DUSD Settlement Pool へ流れます。恩恵はすべての DUSD 保有者に及びます：オンチェーンのウォレット、PancakeSwap/Raydium の LP、Perps ウォレットの未使用 DUSD。SIP-2 の配分とは別会計です。任意の Yield Smoothing Reserve が高出来高期の余剰を蓄え、閑散期の APY を支えます。ステータス：実装済み。",
    },
  },
  {
    id: "sip-4",
    source: "/sip/sip-4-block-options",
    tags: "sip-4 sip4 block options opsiyon tp sl reservation fee guarantee deposit 期权 オプション",
    a: {
      tr: "SIP-4 Block Options, Block Trade üzerine kurulu gecikmeli-icra modu ve ilk sürümde sadece pozisyon TP/SL akışlarında görünüyor. Karşı taraf bir Reservation Fee ödediğinde Amerikan tipi bir icra hakkı kazanır ve vadeye kadar istediği an Execute diyebilir. Block TP'de pozisyon sahibi hakkı satar ve ücreti alır — hak kullanılmadan vade dolarsa hem pozisyonu hem ücreti kalır. Block SL'de pozisyon sahibi ücreti öder ve anlık bir fitille zorla çıkarılmak yerine zamanlama esnekliği kazanır. Yükümlü taraf bir Guarantee Deposit kilitler. Durum: Implemented, yayın 31 Mayıs 2026.",
      en: "SIP-4 Block Options is a deferred-execution mode on top of Block Trade, exposed in V1 only through position TP and SL workflows. Once a counterparty pays a Reservation Fee they hold an American-style execution right and may Execute any time before expiry. In Block TP the position holder sells the right and collects the fee — if it expires unused they keep both the position and the fee. In Block SL the holder pays the fee and buys timing discretion instead of being forced out by a transient wick. The obligated side locks a Guarantee Deposit. Status: Implemented, released 31 May 2026.",
      fr: "SIP-4 Block Options est un mode d'exécution différée bâti sur Block Trade, exposé en V1 uniquement via les flux TP et SL de position. Dès qu'une contrepartie paie une Reservation Fee, elle détient un droit d'exécution de style américain et peut Execute à tout moment avant l'expiration. En Block TP, le détenteur vend le droit et encaisse les frais — si le droit expire, il garde position et frais. En Block SL, il paie les frais et achète de la latitude de timing au lieu d'être sorti par une mèche passagère. La partie obligée bloque un Guarantee Deposit. Statut : Implemented, sorti le 31 mai 2026.",
      zh: "SIP-4 Block Options 是建立在大宗交易之上的延迟执行模式，V1 仅通过仓位 TP/SL 流程开放。对手方支付 Reservation Fee 后即获得美式执行权，可在到期前任意时间 Execute。在 Block TP 中，持仓者出售该权利并收取费用 —— 若到期未行权，仓位和费用都归他。在 Block SL 中，持仓者支付费用换取时机自由度，而不是被瞬时插针强制出局。义务方需锁定 Guarantee Deposit。状态：已实施，2026 年 5 月 31 日发布。",
      ja: "SIP-4 ブロックオプションはブロック取引の上に載る遅延執行モードで、V1 ではポジションの TP/SL フローからのみ利用できます。相手方が Reservation Fee を支払うとアメリカン型の執行権を得て、満期までいつでも Execute できます。Block TP では保有者が権利を売って手数料を受け取り、未行使で満期を迎えればポジションも手数料も残ります。Block SL では保有者が手数料を払い、一瞬のヒゲで強制退出させられる代わりにタイミングの裁量を買います。義務側は Guarantee Deposit をロックします。ステータス：実装済み、2026年5月31日リリース。",
    },
  },
  {
    id: "sip-5",
    source: "/sip/sip-5-universal-markets-listing",
    tags: "sip-5 sip5 universal markets listing izinsiz listeleme permissionless sponsor oracle grid 万能市场 上市",
    a: {
      tr: "SIP-5 Universal Markets, perp listeleme, market yapıcılık ve uzun vadeli gelir haklarını topluluğa iade eden çerçeve. Herkes her varlığı listeleyebilir: büyük kripto, uzun kuyruk token, TGE öncesi token, zincir üstü olaylar. Bir Sponsor DUSD stake ederek Market Slot alır; miktar sabit değil, koşullara göre değişir. Sponsor'ın taahhüt ettiği market yapıcılık bütçesinin %100'ü Reward Vault'a gider — StandX listeleme ücreti almaz. Sponsor'ın ücret payı sağlığa bağlıdır ve piyasa sağlıksız işaretlenirse emanete alınır. Oracle Grid üç katmanlı: Blind, Linked (Pyth/Chainlink) ve Open. Durum: WIP/Review.",
      en: "SIP-5 Universal Markets is the framework that returns perp listing, market making and long-term revenue rights to the community. Anyone can list any asset: major crypto, long-tail tokens, pre-TGE tokens, on-chain events. A Sponsor claims a Market Slot by staking DUSD, and the amount is dynamic rather than fixed. 100% of the Sponsor's committed market-making budget goes to the Reward Vault — StandX takes no listing fee. The Sponsor's fee share is health-conditional and moves to escrow if the market is flagged unhealthy. The Oracle Grid has three tiers: Blind, Linked (Pyth/Chainlink) and Open. Status: WIP/Review.",
      fr: "SIP-5 Universal Markets est le cadre qui rend à la communauté les droits de lister, de market maker et de capter les revenus long terme des perps. N'importe qui peut lister n'importe quel actif : crypto majeure, tokens long tail, tokens pré-TGE, événements on-chain. Un Sponsor obtient un Market Slot en stakant du DUSD, montant dynamique et non fixe. 100 % du budget de market making engagé par le Sponsor va au Reward Vault — StandX ne prend aucun frais de listing. La part de frais du Sponsor est conditionnée à la santé du marché et passe en séquestre si celui-ci est signalé. L'Oracle Grid a trois niveaux : Blind, Linked (Pyth/Chainlink) et Open. Statut : WIP/Review.",
      zh: "SIP-5 Universal Markets 是把永续上市、做市和长期收益权交还社区的框架。任何人都能上任何资产：主流币、长尾代币、TGE 前代币、链上事件。Sponsor 通过质押 DUSD 领取 Market Slot，金额是动态而非固定的。Sponsor 承诺的做市预算 100% 进入 Reward Vault —— StandX 不收上市费。Sponsor 的手续费分成以市场健康为条件，市场被标记为不健康时进入托管。Oracle Grid 分三层：Blind、Linked（Pyth/Chainlink）和 Open。状态：WIP/Review。",
      ja: "SIP-5 Universal Markets は、パープスの上場・マーケットメイク・長期収益の権利をコミュニティに返す枠組みです。誰でもあらゆる資産を上場できます：主要暗号資産、ロングテールトークン、TGE 前トークン、オンチェーンイベント。Sponsor は DUSD をステークして Market Slot を確保し、必要額は固定ではなく動的です。Sponsor が約束したマーケットメイク予算は 100% が Reward Vault に入り、StandX は上場料を取りません。Sponsor の手数料シェアは健全性条件付きで、市場が不健全と判定されるとエスクローされます。Oracle Grid は Blind・Linked（Pyth/Chainlink）・Open の三層です。ステータス：WIP/Review。",
    },
  },
  {
    id: "sip-5a",
    source: "/sip/sip-5a-community-maker-yield",
    tags: "sip-5a community maker yield maker hours 10 bps 30 dakika uptime 做市收益 メイカー 800 btc",
    a: {
      tr: "SIP-5A Community Maker Yield, defterde gerçek ve iki taraflı likidite tutan maker'ları tick seviyesinde ölçüp ödüllendirir. Şartlar: hem alış hem satış tarafında aktif emir, mark fiyatın 10 bps bandı içinde ve saatin en az 30 dakikası. Tek taraflı kotasyon saymaz. Yakınlık önemli: en dar spread'lerde ağırlık 2 katına kadar çıkar. Ödül günlük dağıtılır, DUSD ve/veya platform token tahsisi olarak ödenir. Aylık Maker Saati eşikleri ücret kademesi açar: MM0 250 saat, MM1 360 saat, MM2 504 saat üstü. StandX'in BTC defter derinliği 10 bps içinde 800 BTC'yi aştı. Durum: Implemented.",
      en: "SIP-5A Community Maker Yield measures makers who keep real two-sided liquidity on the book at tick-level granularity and pays them. Requirements: active orders on both bid and ask, inside a 10 bps band of the mark price, for at least 30 minutes of each hour. One-sided quoting does not qualify. Proximity matters: at the tightest spreads weight goes up to 2×. Rewards settle daily and are paid in DUSD and/or platform token allocation. Monthly Maker Hours unlock fee tiers: MM0 at 250 hours, MM1 at 360, MM2 above 504. StandX BTC book depth crossed 800 BTC within a 10 bps spread. Status: Implemented.",
      fr: "SIP-5A Community Maker Yield mesure au tick près les makers qui maintiennent une vraie liquidité bilatérale au carnet, et les rémunère. Conditions : ordres actifs des deux côtés, dans une bande de 10 bps autour du mark, pendant au moins 30 minutes par heure. La cotation unilatérale ne qualifie pas. La proximité compte : au plus serré, le poids monte jusqu'à 2×. Les récompenses sont réglées quotidiennement, en DUSD et/ou en allocation de token. Les Maker Hours mensuelles ouvrent des paliers de frais : MM0 à 250 h, MM1 à 360 h, MM2 au-delà de 504 h. La profondeur BTC de StandX a dépassé 800 BTC dans un spread de 10 bps. Statut : Implemented.",
      zh: "SIP-5A 社区做市收益以 tick 级精度衡量在盘口维持真实双边流动性的做市商并给予回报。条件：买卖两侧都有活跃订单，位于标记价 10 bps 带内，且每小时至少维持 30 分钟。单边报价不合格。邻近度很重要：价差最紧时权重可达 2 倍。奖励每日结算，以 DUSD 和/或平台代币额度支付。月度 Maker Hours 解锁费率档位：MM0 需 250 小时，MM1 需 360 小时，MM2 超过 504 小时。StandX 的 BTC 盘口深度在 10 bps 内已突破 800 BTC。状态：已实施。",
      ja: "SIP-5A コミュニティメイカー利回りは、板に本物の両側流動性を置くメイカーをティック単位で計測し報酬を出します。条件は、買い・売り両側に有効注文があり、マーク価格の 10 bps バンド内で、毎時 30 分以上維持すること。片側だけの提示は対象外です。近さが重要で、最もタイトな水準では重みが最大 2 倍になります。報酬は日次決済で、DUSD および/またはプラットフォームトークン配分で支払われます。月間 Maker Hours で手数料ティアが開き、MM0 は 250 時間、MM1 は 360 時間、MM2 は 504 時間超です。StandX の BTC 板厚は 10 bps 内で 800 BTC を突破しました。ステータス：実装済み。",
    },
  },
  {
    id: "shield-reward-vault",
    source: "/sip/sip-5-universal-markets-listing",
    tags: "shield vault reward vault kalkan ödül kasa adl insurance sigorta 盾 报酬 保険 separation",
    a: {
      tr: "Bir Universal Market'in başlangıç sermayesi kesin biçimde ayrılmış iki vault'a bölünür. Shield Vault zarar emici sigortadır: likidasyon defterde kabul edilebilir fiyatlarla temizlenemezse pozisyonu likidasyon fiyatından devralır ve likidasyon ücretini kazanır. Sadece Shield tükendiğinde ADL tetiklenir. Reward Vault ise maker teşvik bütçesidir ve günlük olarak topluluk maker'larına dağıtılır. Ayrım katıdır: Shield sermayesi asla ödül ödemek için, Reward sermayesi asla likidasyon açığını kapatmak için kullanılmaz. Her piyasa bir `required_reserve_floor` tanımlar; altına düşülürse Watchlist'e alınır ve Sponsor'un ücret payı durur.",
      en: "A Universal Market's initial capital splits into two strictly separated vaults. The Shield Vault is loss-absorbing insurance: when a liquidation cannot clear on the book at acceptable prices it takes the position over at the liquidation price and earns the liquidation fee. Only when the Shield is depleted does ADL trigger. The Reward Vault is the maker incentive budget, paid out daily to community makers. The separation is strict: Shield capital is never used to pay rewards, and Reward capital is never used to absorb liquidation shortfalls. Every market defines a `required_reserve_floor`; falling below it triggers a Watchlist demotion and pauses the Sponsor's fee share.",
      fr: "Le capital initial d'un Universal Market se divise en deux vaults strictement séparés. Le Shield Vault est une assurance absorbant les pertes : quand une liquidation ne peut pas passer au carnet à des prix acceptables, il reprend la position au prix de liquidation et perçoit les frais. L'ADL ne se déclenche que lorsque le Shield est épuisé. Le Reward Vault est le budget d'incitation maker, distribué quotidiennement. La séparation est stricte : le capital Shield ne paie jamais de récompenses, et le capital Reward n'absorbe jamais de pertes de liquidation. Chaque marché définit un `required_reserve_floor` ; passer en dessous entraîne une mise en Watchlist et suspend la part de frais du Sponsor.",
      zh: "一个 Universal Market 的初始资本严格拆分为两个金库。Shield Vault 是吸收亏损的保险：当清算无法在盘口以可接受价格完成时，它按清算价接管仓位并赚取清算费。只有 Shield 耗尽才会触发 ADL。Reward Vault 是做市激励预算，每日分配给社区做市商。两者严格隔离：Shield 资本永不用于支付奖励，Reward 资本永不用于弥补清算缺口。每个市场定义 `required_reserve_floor`，低于该线会被降级到 Watchlist 并暂停 Sponsor 的手续费分成。",
      ja: "Universal Market の初期資本は、厳格に分離された二つの Vault に分かれます。Shield Vault は損失吸収の保険で、清算が板で妥当な価格で消化できない場合に清算価格でポジションを引き受け、清算手数料を得ます。Shield が枯渇して初めて ADL が動きます。Reward Vault はメイカー報酬の予算で、日次でコミュニティメイカーへ配られます。分離は厳格で、Shield 資本が報酬に使われることも、Reward 資本が清算不足の穴埋めに使われることもありません。各市場は `required_reserve_floor` を定め、下回ると Watchlist へ降格し Sponsor の手数料シェアが停止します。",
    },
  },
  {
    id: "contract-specs",
    source: "/docs/standx-perps-solutions/contract-specifications",
    tags: "pariteler pairs symbols semboller btc eth sol gold xau tsla listeleme 交易对 銘柄 max leverage",
    a: {
      tr: "Şu an 11 işlem çifti listeli ve üç sınıfa yayılıyor: kripto (BTC, ETH, BNB, SOL, HYPE), emtia (XAU altın, XAG gümüş, CL ham petrol) ve hisse (TSLA, SPCX, MU). Maksimum kaldıraçlar: BTC, ETH, CL, XAU ve XAG 40x; BNB ve SOL 30x; HYPE, TSLA, SPCX ve MU 20x. Minimum işlem miktarı BTC'de 0,0001, ETH'de 0,001, SOL'de 0,01. Bu tablo düzensiz aralıklarla güncellenir; kesin bilgi canlı işlem verisidir.",
      en: "Eleven trading pairs are listed today across three classes: crypto (BTC, ETH, BNB, SOL, HYPE), commodities (XAU gold, XAG silver, CL crude oil) and equities (TSLA, SPCX, MU). Max leverage: 40x on BTC, ETH, CL, XAU and XAG; 30x on BNB and SOL; 20x on HYPE, TSLA, SPCX and MU. Minimum trade size is 0.0001 BTC, 0.001 ETH, 0.01 SOL. The table is updated irregularly, so live trading data is the source of truth.",
      fr: "Onze paires sont listées aujourd'hui, réparties en trois classes : crypto (BTC, ETH, BNB, SOL, HYPE), matières premières (XAU or, XAG argent, CL pétrole) et actions (TSLA, SPCX, MU). Levier max : 40x sur BTC, ETH, CL, XAU et XAG ; 30x sur BNB et SOL ; 20x sur HYPE, TSLA, SPCX et MU. Taille minimale : 0,0001 BTC, 0,001 ETH, 0,01 SOL. Le tableau est mis à jour irrégulièrement, la donnée de trading en direct fait foi.",
      zh: "目前上线 11 个交易对，覆盖三类：加密（BTC、ETH、BNB、SOL、HYPE）、商品（XAU 黄金、XAG 白银、CL 原油）和股票（TSLA、SPCX、MU）。最大杠杆：BTC、ETH、CL、XAU、XAG 为 40 倍；BNB、SOL 为 30 倍；HYPE、TSLA、SPCX、MU 为 20 倍。最小下单量：BTC 0.0001、ETH 0.001、SOL 0.01。该表更新不定期，以实时交易数据为准。",
      ja: "現在 11 銘柄が上場しており、三つのクラスにまたがります：暗号資産（BTC・ETH・BNB・SOL・HYPE）、コモディティ（XAU 金・XAG 銀・CL 原油）、株式（TSLA・SPCX・MU）。最大レバレッジは BTC・ETH・CL・XAU・XAG が 40 倍、BNB・SOL が 30 倍、HYPE・TSLA・SPCX・MU が 20 倍。最小取引数量は BTC 0.0001、ETH 0.001、SOL 0.01。この表は不定期更新のため、ライブの取引データが最終的な情報源です。",
    },
  },
  {
    id: "api",
    source: "/standx-api/standx-api",
    tags: "api rest websocket bot geliştirici developer jwt rate limit 接口 開発 ws endpoint",
    a: {
      tr: "StandX perps için REST ve WebSocket API sunar. Temel adres https://perps.standx.com. Kimlik doğrulama cüzdan imzasıyla alınan JWT ile yapılır ve token 7 gün geçerlidir; geliştirme ortamının ed25519 desteklemesi gerekir. Market akışı wss://perps.standx.com/ws-stream/v1, emir yanıt akışı wss://perps.standx.com/ws-api/v1. Bir WebSocket bağlantısı en fazla 24 saat yaşar, sunucu 10 saniyede bir ping gönderir. Hız limiti kredi tabanlı: istek başına 45 kredi, saniyede 1000 kredi yenilenir, sürekli hız yaklaşık 22 istek/saniye, IP başına 50 istek/saniye ve en fazla 10 WebSocket bağlantısı.",
      en: "StandX offers REST and WebSocket APIs for perps. The base URL is https://perps.standx.com. Authentication uses a JWT obtained through a wallet signature and the token is valid for 7 days; your environment must support ed25519. The market stream is wss://perps.standx.com/ws-stream/v1 and the order response stream is wss://perps.standx.com/ws-api/v1. A WebSocket connection lives at most 24 hours and the server pings every 10 seconds. Rate limiting is credit-based: 45 credits per request, 1,000 credits replenished per second, about 22 requests/second sustained, 50 requests/second per IP and a maximum of 10 WebSocket connections.",
      fr: "StandX propose des API REST et WebSocket pour les perps. URL de base : https://perps.standx.com. L'authentification utilise un JWT obtenu par signature de portefeuille, valide 7 jours ; l'environnement doit supporter ed25519. Le flux marché est wss://perps.standx.com/ws-stream/v1 et le flux de réponse d'ordre wss://perps.standx.com/ws-api/v1. Une connexion WebSocket vit au maximum 24 heures et le serveur ping toutes les 10 secondes. Limitation par crédits : 45 crédits par requête, 1 000 crédits rechargés par seconde, environ 22 requêtes/seconde en continu, 50 requêtes/seconde par IP et 10 connexions WebSocket maximum.",
      zh: "StandX 为永续提供 REST 和 WebSocket API。基础地址是 https://perps.standx.com。认证使用通过钱包签名获取的 JWT，令牌有效期 7 天；开发环境需支持 ed25519。行情流为 wss://perps.standx.com/ws-stream/v1，订单响应流为 wss://perps.standx.com/ws-api/v1。单个 WebSocket 连接最长存活 24 小时，服务端每 10 秒发送 ping。限流基于信用额：每请求 45 信用，每秒补充 1000 信用，持续约 22 请求/秒，单 IP 50 请求/秒，最多 10 个 WebSocket 连接。",
      ja: "StandX はパープス向けに REST と WebSocket API を提供します。ベース URL は https://perps.standx.com。認証はウォレット署名で取得する JWT を使い、トークンの有効期間は 7 日です。環境は ed25519 に対応している必要があります。マーケットストリームは wss://perps.standx.com/ws-stream/v1、注文レスポンスは wss://perps.standx.com/ws-api/v1。WebSocket 接続は最大 24 時間で、サーバーは 10 秒ごとに ping を送ります。レート制限はクレジット制で、1 リクエスト 45 クレジット、毎秒 1,000 クレジット回復、持続で約 22 リクエスト/秒、IP あたり 50 リクエスト/秒、WebSocket は最大 10 接続です。",
    },
  },
  {
    id: "security",
    source: "/docs/resources/audits",
    tags: "güvenlik security audit denetim watchpug rigsec custodian saklama 安全 审计 監査 risk",
    a: {
      tr: "Altı denetim raporu yayında, iki firmadan: WatchPug ve RigSec. Raporlar hem DUSD sözleşmelerini hem Highway (köprü/çekim) sözleşmelerini, Solana/SVM ve EVM tarafında kapsıyor ve hepsi standx-labs/stand_audit GitHub deposunda açık. Bunun yanında karşı taraf riskini önlemek için saklama çözümü, destek varlıklarındaki olası zararı karşılamak için rezerv fonu, zaman kilitli yükseltmeler, otomatik izleme ve acil durum duraklatma var. Oracle tarafında birden fazla bağımsız fiyat beslemesi, medyan seçimi, sapma eşikleri ve yedek olarak TWAP kullanılıyor.",
      en: "Six audit reports are published from two firms: WatchPug and RigSec. They cover both the DUSD contracts and the Highway (bridge/withdrawal) contracts on Solana/SVM and EVM, and all of them are public in the standx-labs/stand_audit GitHub repository. Alongside that: a custodian solution to avoid counterparty risk, a reserve fund against losses in backing assets, time-locked upgrades, automated monitoring and emergency pause. On the oracle side there are multiple independent price feeds, median selection, deviation thresholds and TWAP as fallback.",
      fr: "Six rapports d'audit sont publiés par deux cabinets : WatchPug et RigSec. Ils couvrent les contrats DUSD et les contrats Highway (pont/retrait) sur Solana/SVM et EVM, tous publics dans le dépôt GitHub standx-labs/stand_audit. À cela s'ajoutent une solution de conservation contre le risque de contrepartie, un fonds de réserve contre les pertes sur actifs de garantie, des mises à jour verrouillées dans le temps, une surveillance automatisée et une pause d'urgence. Côté oracle : plusieurs flux de prix indépendants, sélection médiane, seuils de déviation et TWAP en repli.",
      zh: "已发布六份审计报告，来自两家机构：WatchPug 和 RigSec。覆盖 DUSD 合约以及 Highway（跨链/提现）合约，涵盖 Solana/SVM 和 EVM，全部公开在 standx-labs/stand_audit GitHub 仓库。此外还有：避免对手方风险的托管方案、应对抵押资产损失的储备基金、时间锁升级、自动化监控和紧急暂停。预言机方面采用多个独立价格源、中位数选取、偏离阈值，并以 TWAP 作为兜底。",
      ja: "監査レポートは 2 社から 6 本公開されています：WatchPug と RigSec。DUSD コントラクトと Highway（ブリッジ／出金）コントラクトを Solana/SVM と EVM の両方でカバーし、すべて standx-labs/stand_audit の GitHub リポジトリで公開されています。加えて、カウンターパーティリスクを避けるカストディ体制、裏付け資産の損失に備える準備金、タイムロック付きアップグレード、自動監視、緊急停止機能があります。オラクル側では複数の独立系価格フィード、中央値選択、乖離しきい値、フォールバックの TWAP を使用します。",
    },
  },
  {
    id: "mainnet",
    source: "/docs/standx-earn",
    tags: "mainnet ne zaman launch lansman 24 kasım november 2025 chains zincir bnb solana 主网 メインネット",
    a: {
      tr: "StandX ana ağı 24 Kasım 2025'te canlıya geçti. Platform BNB Chain ve Solana üzerinde çalışıyor; DUSD Solana'da Token 2022 programı, BSC'de BEP-20 standardında. Ana ağ öncesinde Pre-Deposit kampanyası (31 Ekim 2025'te bitti) ve tDUSD ile oynanan Alpha aşaması (3–24 Kasım 2025) vardı; Alpha'da gerçek sermaye hiç risk almadı ve kazanılan puanlar korunarak taşındı. Büyük Mainnet İşlem Puanı kampanyası 10 Aralık 2025'te başladı.",
      en: "StandX Mainnet went live on 24 November 2025. The platform runs on BNB Chain and Solana; DUSD is a Token 2022 program asset on Solana and BEP-20 on BSC. Before mainnet there was a Pre-Deposit campaign (ended 31 October 2025) and an Alpha phase played with tDUSD (3–24 November 2025), where real capital was never at risk and earned points carried over. The grand Mainnet Trading Points campaign started on 10 December 2025.",
      fr: "Le mainnet StandX a été lancé le 24 novembre 2025. La plateforme tourne sur BNB Chain et Solana ; DUSD est un actif Token 2022 sur Solana et BEP-20 sur BSC. Avant le mainnet, il y a eu une campagne Pre-Deposit (terminée le 31 octobre 2025) et une phase Alpha jouée en tDUSD (3–24 novembre 2025), où le capital réel n'a jamais été exposé et les points acquis ont été conservés. La grande campagne Mainnet Trading Points a démarré le 10 décembre 2025.",
      zh: "StandX 主网于 2025 年 11 月 24 日上线。平台运行在 BNB Chain 和 Solana 上；DUSD 在 Solana 为 Token 2022 程序资产，在 BSC 为 BEP-20。主网之前有 Pre-Deposit 活动（2025 年 10 月 31 日结束）和使用 tDUSD 的 Alpha 阶段（2025 年 11 月 3–24 日），Alpha 期间真实资金从未承担风险，所获积分予以保留。大型主网交易积分活动于 2025 年 12 月 10 日启动。",
      ja: "StandX メインネットは 2025年11月24日に稼働開始しました。プラットフォームは BNB Chain と Solana で動作し、DUSD は Solana では Token 2022、BSC では BEP-20 です。メインネット前には Pre-Deposit キャンペーン（2025年10月31日終了）と tDUSD による Alpha フェーズ（2025年11月3〜24日）があり、Alpha では実資金が危険にさらされることはなく、獲得ポイントは引き継がれました。大型のメインネット取引ポイントキャンペーンは 2025年12月10日に開始しました。",
    },
  },
  {
    id: "dividend",
    source: "/docs/standx-perps-solutions/dividend-adjustment",
    tags: "dividend temettü hisse stock perps tsla ex-date split 股息 配当 adjustment",
    a: {
      tr: "Hisse perp'lerinde pozisyon sadece temettü sonrası fiyat düşüşünü görür, temettüyü almaz; bu long'u cezalandırıp short'a bedava kazanç verirdi. StandX bunu temettü düzeltmesiyle çözer: temettü değerine tam eşit, tek seferlik bir funding transferi short'tan long'a yapılır. StandX bundan hiçbir şey almaz. Nakit temettü oranı = −D / M (D hisse başına brüt temettü, M anlık mark fiyat). Örnek: 200 dolarlık hissede 1,50 dolar temettü %−0,75 demektir. ABD hisselerinde ex-tarihten önceki günün 20:00 ET'sinde, Kore hisselerinde ex-tarihte 08:00 KST'de işlenir; 30 dakika önce reduce-only moda geçilir. Bu düzeltme saatlik %4 funding tavanını kasten dikkate almaz.",
      en: "On stock perps a position only sees the ex-dividend price drop, not the payout, which would punish longs and gift shorts. StandX fixes this with a dividend adjustment: a one-time funding settlement exactly equal to the dividend value, paid from shorts to longs. StandX takes nothing from it. The cash dividend rate is −D / M, where D is the gross dividend per share and M the live mark price. Example: a $1.50 dividend on a $200 stock gives −0.75%. It settles at 20:00 ET the day before the ex-date for US stocks, and 08:00 KST on the ex-date for Korean stocks, with reduce-only mode 30 minutes before. The adjustment deliberately ignores the 4% hourly funding cap.",
      fr: "Sur les perps actions, une position ne voit que la baisse de prix ex-dividende, pas le versement, ce qui pénaliserait les longs et avantagerait les shorts. StandX corrige par un ajustement de dividende : un règlement de funding unique, exactement égal à la valeur du dividende, payé des shorts aux longs. StandX ne prélève rien. Le taux du dividende en cash est −D / M, D étant le dividende brut par action et M le prix mark. Exemple : 1,50 $ de dividende sur une action à 200 $ donne −0,75 %. Règlement à 20:00 ET la veille de l'ex-date pour les actions US, et 08:00 KST le jour de l'ex-date pour les actions coréennes, avec mode reduce-only 30 minutes avant. L'ajustement ignore volontairement le plafond de funding de 4 % par heure.",
      zh: "在股票永续中，仓位只承受除息后的价格下跌，却拿不到股息，这会惩罚多头、白送空头。StandX 用股息调整解决：一次性资金费结算，金额恰好等于股息价值，由空头付给多头。StandX 不从中抽取任何费用。现金股息费率为 −D / M，D 为每股总股息，M 为实时标记价格。例如：200 美元股票派息 1.50 美元，即 −0.75%。美股在除息日前一天 20:00 ET 结算，韩股在除息日 08:00 KST 结算，提前 30 分钟进入只减仓模式。该调整刻意不受每小时 4% 资金费上限约束。",
      ja: "株式パープスではポジションは配当落ちの価格下落だけを被り、配当は受け取れません。これではロングが罰せられショートが得をします。StandX は配当調整で解決します：配当額とちょうど同額の一回限りのファンディング決済を、ショートからロングへ支払います。StandX は一切取りません。現金配当のレートは −D / M（D は 1 株あたり総配当、M は約定時のマーク価格）。例：200 ドルの株で 1.50 ドルの配当なら −0.75%。米国株は権利落ち日前日の 20:00 ET、韓国株は権利落ち日の 08:00 KST に決済され、30 分前からリデュースオンリーになります。この調整は毎時 4% のファンディング上限を意図的に無視します。",
    },
  },
  {
    id: "mascot",
    source: "/docs/resources/media-assets",
    tags: "stander maskot mascot logo marka brand asset indir download 吉祥物 マスコット gallery",
    a: {
      tr: "Stander, StandX'in maskotu — δ harfinden türemiş, tek gözlü, tepesinde yapraklı bir karakter. Resmî marka varlıkları PNG veya SVG olarak indirilebiliyor, ayrıca panoya doğrudan kopyalama seçeneği var. Kurallar net: orijinal oranları ve etrafındaki boşluğu koru, işareti yeniden renklendirme veya bozma; koyu zeminde açık sürümü, açık zeminde koyu sürümü kullan. İkonun iki varyantı var: Default (dar kırpılmış) ve Small (küçük boyutlar için paylı). Stander'ın tam karakter sayfaları ve ifadeleri gallery.standx.org adresinde.",
      en: "Stander is the StandX mascot — a one-eyed character grown out of the δ mark, with a leaf on top. Official brand assets download as PNG or SVG, and there is a copy-to-clipboard option. The rules are clear: keep the original proportions and clear space, do not recolor or distort the marks, and use the light version on dark backgrounds and the dark version on light. The icon has two variants: Default (tightly cropped) and Small (padded for small sizes). Full Stander character sheets and expressions live at gallery.standx.org.",
      fr: "Stander est la mascotte de StandX — un personnage borgne né de la marque δ, avec une feuille sur la tête. Les assets officiels se téléchargent en PNG ou SVG, avec une option copier dans le presse-papiers. Les règles sont claires : garder les proportions et l'espace de respiration, ne pas recolorer ni déformer, version claire sur fond sombre et version sombre sur fond clair. L'icône a deux variantes : Default (recadrée serré) et Small (avec marge pour les petites tailles). Les planches complètes de Stander sont sur gallery.standx.org.",
      zh: "Stander 是 StandX 的吉祥物 —— 由 δ 标识演化出的独眼角色，头顶一片叶子。官方品牌素材可下载 PNG 或 SVG，并支持一键复制到剪贴板。规则很明确：保持原始比例与留白，不要改色或变形，深色背景用浅色版、浅色背景用深色版。图标有两个变体：Default（紧密裁切）和 Small（为小尺寸添加留白）。完整的 Stander 角色设定与表情在 gallery.standx.org。",
      ja: "Stander は StandX のマスコットで、δ マークから生まれた一つ目のキャラクター、頭に葉が付いています。公式ブランド素材は PNG または SVG でダウンロードでき、クリップボードへのコピーも用意されています。ルールは明確です：元の比率と余白を保つ、色を変えたり歪めたりしない、暗い背景には明るい版、明るい背景には暗い版。アイコンには Default（タイトなトリミング）と Small（小サイズ用に余白付き）の 2 種類があります。Stander の完全なキャラクターシートと表情は gallery.standx.org にあります。",
    },
  },
  {
    id: "poker-ui",
    source: "/docs/standx-perps-overview",
    tags: "poker table arayüz ui market monitor execution panel order book defter 扑克 ポーカー interface",
    a: {
      tr: "StandX arayüzü pokerden esinlenir ve ikiye ayrılır: Market Monitor (poker masası) ve Execution Panel (elindeki kartlar). Market Monitor'da mum grafiği, akışkan emir defteri ve son işlemler var. Emir defteri statik bir liste değil: ortada canlı spread'i gösteren mavi bir çizgi, altında anlık değişim var, iki sürüklenebilir yatay çizgiyle görünüm aralığını daraltabilir ve tüm defteri kaydırarak gizli büyük emirleri bulabilirsin. Execution Panel ekranın altında; solda emir girişi, sağda önce açık pozisyonlar, her pozisyonun altında ona bağlı TP/SL emirleri listelenir.",
      en: "The StandX interface is inspired by poker and splits in two: the Market Monitor (the table) and the Execution Panel (your hand). The Market Monitor holds the candle chart, the fluid order book and latest trades. The order book is not a static list: a blue line marks the live spread with the immediate delta beneath it, two draggable horizontal lines let you narrow the visual range, and the whole book scrolls so you can find large hidden orders. The Execution Panel sits at the bottom — order entry on the left, and on the right open positions first, with their attached TP/SL orders nested underneath.",
      fr: "L'interface StandX s'inspire du poker et se divise en deux : le Market Monitor (la table) et l'Execution Panel (ta main). Le Market Monitor contient le graphique en chandeliers, le carnet fluide et les derniers trades. Le carnet n'est pas une liste statique : une ligne bleue marque le spread en direct avec le delta immédiat en dessous, deux lignes horizontales déplaçables permettent de resserrer la plage visuelle, et tout le carnet défile pour repérer les gros ordres cachés. L'Execution Panel est en bas — saisie d'ordre à gauche, positions ouvertes en priorité à droite, avec leurs TP/SL imbriqués dessous.",
      zh: "StandX 界面受扑克启发，分为两部分：Market Monitor（牌桌）和 Execution Panel（你的手牌）。Market Monitor 包含 K 线图、流动订单簿和最新成交。订单簿不是静态列表：中间用蓝线标出实时价差，下方显示即时变动，两条可拖动的水平线可收窄显示区间，整个订单簿可滚动以发现隐藏的大单。Execution Panel 位于底部 —— 左侧下单，右侧优先展示持仓，每个持仓下方嵌套其 TP/SL 订单。",
      ja: "StandX の UI はポーカー着想で二つに分かれます：Market Monitor（テーブル）と Execution Panel（自分の手札）。Market Monitor にはローソク足チャート、流動的な板、直近約定が並びます。板は静的なリストではなく、中央の青線がライブのスプレッドを示し、その下に即時の変化量が出ます。ドラッグできる水平線 2 本で表示レンジを絞れ、板全体をスクロールして隠れた大口注文を見つけられます。Execution Panel は画面下部にあり、左が発注、右は建玉が優先表示され、その下に紐づく TP/SL がぶら下がります。",
    },
  },
  {
    id: "geo",
    source: "/docs/resources/user-terms-conditions",
    tags: "geo block yasak ülke restricted country kyc terms şartlar 地区 限制 規制 issuer bvi",
    a: {
      tr: "İhraççı, Britanya Virjin Adaları'nda kurulu StandX Issuer Ltd (şirket no 2163662). Kullanıcıların en az 18 yaşında olması gerekiyor. Coğrafi olarak engellenen yargı bölgeleri arasında Amerika Birleşik Devletleri, Birleşik Krallık, Rusya, İran, Küba, Kuzey Kore, Suriye, Venezuela ve başkaları var. İhraççıyla doğrudan alım veya redeem için \"Greenlisted\" olmak, yani onboarding ile KYC/AML sürecini tamamlamak gerekiyor. Uygulanacak hukuk İngiltere ve Galler hukuku; uyuşmazlıklar LCIA kuralları uyarınca Londra'da üç hakemle tahkime gidiyor.",
      en: "The issuer is StandX Issuer Ltd, incorporated in the British Virgin Islands (company number 2163662). Users must be at least 18. Geo-blocked jurisdictions include the United States, the United Kingdom, Russia, Iran, Cuba, DPR Korea, Syria, Venezuela and others. Buying or redeeming directly with the issuer requires being \"Greenlisted\", meaning completing onboarding plus KYC/AML. Governing law is the laws of England and Wales, and disputes go to arbitration in London under LCIA rules with three arbitrators.",
      fr: "L'émetteur est StandX Issuer Ltd, constituée aux Îles Vierges britanniques (numéro 2163662). Les utilisateurs doivent avoir au moins 18 ans. Les juridictions géo-bloquées incluent les États-Unis, le Royaume-Uni, la Russie, l'Iran, Cuba, la Corée du Nord, la Syrie, le Venezuela et d'autres. Acheter ou racheter directement auprès de l'émetteur exige d'être « Greenlisted », c'est-à-dire d'avoir complété l'onboarding et le KYC/AML. Le droit applicable est celui de l'Angleterre et du Pays de Galles ; les litiges vont en arbitrage à Londres selon les règles LCIA avec trois arbitres.",
      zh: "发行方是在英属维尔京群岛注册的 StandX Issuer Ltd（公司编号 2163662）。用户须年满 18 岁。地理封锁的司法辖区包括美国、英国、俄罗斯、伊朗、古巴、朝鲜、叙利亚、委内瑞拉等。直接向发行方申购或赎回需要成为 “Greenlisted”，即完成入驻和 KYC/AML。适用法律为英格兰和威尔士法律；争议依 LCIA 规则在伦敦由三名仲裁员仲裁。",
      ja: "発行体は英領ヴァージン諸島設立の StandX Issuer Ltd（会社番号 2163662）です。利用者は 18 歳以上である必要があります。ジオブロック対象の法域には米国、英国、ロシア、イラン、キューバ、北朝鮮、シリア、ベネズエラなどが含まれます。発行体と直接の購入・償還を行うには「Greenlisted」、すなわちオンボーディングと KYC/AML の完了が必要です。準拠法はイングランド及びウェールズ法で、紛争は LCIA 規則に基づきロンドンで仲裁人 3 名により解決されます。",
    },
  },
  {
    id: "discord-join",
    source: "/blog/articles/standx-recap-of-milestones-activities-and-ecosystem-evolution-p1",
    tags: "discord discort discrod sunucu server katıl join davet invite link topluluk community nereye nasıl girilir gir 加入 サーバー 参加",
    a: {
      tr: "StandX Discord sunucusuna resmî davet linkiyle katıl: discord.gg/standx. Girdikten sonra sunucunun istediği doğrulamayı (captcha, kuralları kabul vb.) tamamla; aksi halde kanalları göremezsin. Discord, duyuruların, kampanyaların, squad'ların, town hall'ların ve destek biletlerinin merkezi — resmî X hesabı ve standx.com'daki linkler de aynı adrese yönlendirir.",
      en: "Join the StandX Discord through the official invite: discord.gg/standx. After joining, complete whatever verification the server asks for (captcha, rules acceptance, etc.) or you will not see the channels. Discord is the hub for announcements, campaigns, squads, town halls and support tickets — the official X account and standx.com links point to the same address.",
      fr: "Rejoins le Discord StandX via l'invitation officielle : discord.gg/standx. Une fois dedans, complète la vérification demandée (captcha, acceptation des règles, etc.) sinon les salons restent invisibles. Discord est le centre des annonces, campagnes, squads, town halls et tickets support — le compte X officiel et les liens standx.com mènent à la même adresse.",
      zh: "通过官方邀请链接加入 StandX Discord：discord.gg/standx。加入后完成服务器要求的验证（验证码、接受规则等），否则看不到频道。Discord 是公告、活动、小队、社区会议和支持工单的中心 —— 官方 X 账号和 standx.com 的链接都指向同一地址。",
      ja: "StandX Discord には公式招待 discord.gg/standx から参加します。参加後、サーバーが求める認証（captcha、ルール同意など）を完了しないとチャンネルが見えません。Discord は告知・キャンペーン・スクワッド・タウンホール・サポートチケットの中心で、公式 X と standx.com のリンクも同じ先です。",
    },
  },
  {
    id: "discord-roles",
    source: "/blog/articles/standx-recap-of-milestones-activities-and-ecosystem-evolution-p1",
    tags: "discord discort rol role roles rütbe rank nasıl alınır how get earn kazan verification doğrulama 角色 ロール 取得 怎么",
    a: {
      tr: "StandX Discord'da roller birkaç yoldan gelir: (1) Growth Path — Engage Point biriktirip @SEED, @SPROUT, @FLOWER gibi katkı rollerine başvurmak; (2) kampanyalar — #StandX-Campaign'deki günlük görevler, davet ve etkinlikler; (3) token doğrulama — belirli token'ları cüzdanda tutup resmî bot/kanal ile kanıtlamak (ör. @ASTER); (4) işlem rolleri — @Active Trader, @Hardcore Trader gibi perps aktivitesine göre dağıtılanlar; (5) dönemsel etkinlik rolleri — duyuruda süre ve şart yazar. Rolleri elle vermezsin; sunucudaki ilgili kanal, bot veya başvuru adımlarını takip et.",
      en: "On StandX Discord, roles come through several paths: (1) Growth Path — earn Engage Points and apply for contribution roles like @SEED, @SPROUT, @FLOWER; (2) campaigns — daily missions, invites and events in #StandX-Campaign; (3) token verification — hold specific tokens in your wallet and prove it via the official bot/channel (e.g. @ASTER); (4) trading roles — @Active Trader, @Hardcore Trader and similar, distributed from perps activity; (5) time-limited event roles — terms and deadlines are in the announcement. You do not assign roles yourself; follow the relevant channel, bot or application steps in the server.",
      fr: "Sur le Discord StandX, les rôles passent par plusieurs voies : (1) Growth Path — accumuler des Engage Points et postuler pour @SEED, @SPROUT, @FLOWER ; (2) campagnes — missions quotidiennes, invitations et événements dans #StandX-Campaign ; (3) vérification token — détenir certains tokens et le prouver via le bot/canal officiel (ex. @ASTER) ; (4) rôles trading — @Active Trader, @Hardcore Trader selon l'activité perps ; (5) rôles d'événement limités — conditions et dates dans l'annonce. Tu ne t'attribues pas les rôles toi-même ; suis le salon, le bot ou la procédure indiquée.",
      zh: "在 StandX Discord 上，角色通过几种途径获得：(1) Growth Path — 积累 Engage Point 并申请 @SEED、@SPROUT、@FLOWER 等贡献角色；(2) 活动 — #StandX-Campaign 中的每日任务、邀请和社区活动；(3) 代币验证 — 在钱包持有特定代币并通过官方 bot/频道验证（如 @ASTER）；(4) 交易角色 — 根据永续活动发放的 @Active Trader、@Hardcore Trader 等；(5) 限时活动角色 — 条件和截止时间在公告中说明。角色不能自行添加，需按服务器内对应频道、bot 或申请步骤操作。",
      ja: "StandX Discord のロールは複数の経路があります。(1) Growth Path — Engage Point を貯め @SEED・@SPROUT・@FLOWER などの貢献ロールに応募；(2) キャンペーン — #StandX-Campaign のデイリーミッション・招待・イベント；(3) トークン認証 — 特定トークンをウォレットで保有し公式 bot/チャンネルで証明（例 @ASTER）；(4) 取引ロール — パープス活動に基づく @Active Trader・@Hardcore Trader など；(5) 期間限定イベントロール — 条件と期限は告知に記載。自分でロールは付けられず、該当チャンネル・bot・申請手順に従います。",
    },
  },
  {
    id: "discord-growth-path",
    source: "/blog/articles/standx-recap-of-milestones-activities-and-ecosystem-evolution-p1",
    tags: "engage point growth path seed sprout flower tier katkı contribution 成长 路径 积分 シード スプロウト",
    a: {
      tr: "StandX Growth Path, Discord'daki ilerleme sistemidir ve Engage Point ile ölçülür — sadece spam değil, gerçek katkı sayılır. 3.000 Engage Point biriktirince Tier 3 (@SEED) başvurusu açılır; oradan @SPROUT (Tier 2) ve @FLOWER (Tier 1) yoluna ilerlenebilir. StandX ID de bu yolculuğun parçası. Puanların ve başvuru adımlarının güncel detayı sunucudaki Growth Path / Engage kanallarında; kampanya dönemlerinde puan çarpanları duyurulabilir.",
      en: "The StandX Growth Path is the Discord progression system measured by Engage Points — real contribution, not just spam. At 3,000 Engage Points you can apply for Tier 3 (@SEED), then progress toward @SPROUT (Tier 2) and @FLOWER (Tier 1). StandX ID is part of this journey. Current point totals and application steps live in the server's Growth Path / Engage channels; campaign periods may announce point multipliers.",
      fr: "Le StandX Growth Path est le système de progression Discord mesuré en Engage Points — contribution réelle, pas du spam. À 3 000 Engage Points, tu peux postuler pour le Tier 3 (@SEED), puis viser @SPROUT (Tier 2) et @FLOWER (Tier 1). StandX ID fait partie de ce parcours. Les totaux et étapes de candidature sont dans les salons Growth Path / Engage ; les campagnes peuvent annoncer des multiplicateurs.",
      zh: "StandX Growth Path 是 Discord 上的进阶体系，以 Engage Point 衡量 —— 看重真实贡献而非刷屏。积累 3,000 Engage Point 后可申请 Tier 3（@SEED），进而向 @SPROUT（Tier 2）和 @FLOWER（Tier 1）进阶。StandX ID 也是这条路径的一部分。最新积分和申请步骤在服务器的 Growth Path / Engage 频道；活动期间可能公布积分倍数。",
      ja: "StandX Growth Path は Discord の進行システムで、Engage Point で測られます — スパムではなく実際の貢献が対象です。3,000 Engage Point で Tier 3（@SEED）に応募でき、@SPROUT（Tier 2）→ @FLOWER（Tier 1）へ進めます。StandX ID もこの旅の一部です。最新のポイントと申請手順は Growth Path / Engage チャンネルにあり、キャンペーン期間中は倍率が告知されることがあります。",
    },
  },
  {
    id: "discord-campaigns",
    source: "/blog/articles/top-10-stablecoin-10-000-standers-stand-x-is-just-getting-started",
    tags: "discord kampanya campaign mission görev daily günlük davet invite friend arkadaş puan point #standx-campaign 活动 任务",
    a: {
      tr: "Discord kampanyaları genelde #StandX-Campaign kanalında yürür. Günlük görevleri tamamla, arkadaş davet et, duyurulan etkinliklere katıl — karşılığında kampanya puanı ve bazen özel rol alırsın. Yoğun dönemlerde puanlar ikiye katlanabilir; duyuruları kaçırma. Kampanya şartları her seferinde farklı olabilir; aktif olan etkinliğin mesajındaki adımları takip et.",
      en: "Discord campaigns usually run in #StandX-Campaign. Complete daily missions, invite friends and join announced events — you earn campaign points and sometimes exclusive roles. During busy periods points may be doubled; watch the announcements. Each campaign can have different rules; follow the steps in the active event message.",
      fr: "Les campagnes Discord tournent surtout dans #StandX-Campaign. Complète les missions quotidiennes, invite des amis et participe aux événements annoncés — tu gagnes des points de campagne et parfois des rôles exclusifs. En période active les points peuvent être doublés ; suis les annonces. Chaque campagne a ses règles ; suis les étapes du message de l'événement en cours.",
      zh: "Discord 活动通常在 #StandX-Campaign 频道进行。完成每日任务、邀请好友、参与公告活动 —— 可获得活动积分，有时还有专属角色。繁忙时期积分可能翻倍，留意公告。每次活动规则可能不同，按当前活动消息中的步骤操作。",
      ja: "Discord キャンペーンは主に #StandX-Campaign で行われます。デイリーミッション達成、友達招待、告知イベント参加でキャンペーンポイントや限定ロールがもらえることがあります。繁忙期はポイント 2 倍になることも — 告知を確認してください。キャンペーンごとに条件が異なるので、進行中のイベントメッセージの手順に従います。",
    },
  },
  {
    id: "discord-support",
    source: "/blog/articles/standx-recap-of-milestones-activities-and-ecosystem-evolution-p1",
    tags: "discord destek support ticket bilet yardım help sorun problem şikayet squad town hall kanal channel 支持 工单",
    a: {
      tr: "StandX Discord'da duyurular, genel sohbet, squad'lar ve town hall'lar ayrı kanallarda. StandX veya DUSD ile ilgili teknik destek için sunucudaki bilet (ticket) sistemi var — doğrudan DM yerine ticket aç. Rol, puan veya kampanya sorunlarında önce ilgili duyuru kanalına ve Growth Path / Campaign kanallarına bak; orada bot komutları ve güncel adımlar yazar.",
      en: "On StandX Discord, announcements, general chat, squads and town halls sit in separate channels. For StandX or DUSD technical support there is a ticket system in the server — open a ticket rather than DMing staff directly. For role, point or campaign issues, check the relevant announcement channel and the Growth Path / Campaign channels first; bot commands and current steps are posted there.",
      fr: "Sur le Discord StandX, annonces, chat général, squads et town halls sont dans des salons séparés. Pour le support technique StandX ou DUSD, un système de tickets existe — ouvre un ticket plutôt qu'un MP direct. Pour rôles, points ou campagnes, consulte d'abord le salon d'annonces et les salons Growth Path / Campaign ; commandes bot et étapes y sont publiées.",
      zh: "StandX Discord 上，公告、闲聊、小队和社区会议分在不同频道。StandX 或 DUSD 的技术支持使用服务器内的工单系统 —— 请开 ticket，不要直接私信工作人员。角色、积分或活动问题，先查看相关公告频道和 Growth Path / Campaign 频道；bot 命令和最新步骤会发布在那里。",
      ja: "StandX Discord では告知・雑談・スクワッド・タウンホールが別チャンネルに分かれています。StandX や DUSD の技術サポートはサーバー内のチケットシステムを使い — 直接 DM より ticket を開いてください。ロール・ポイント・キャンペーンの問題は、まず告知チャンネルと Growth Path / Campaign チャンネルを確認。bot コマンドと最新手順が掲載されています。",
    },
  },
  {
    id: "discord-token-roles",
    source: "/blog/articles/standx-recap-of-milestones-activities-and-ecosystem-evolution-p1",
    tags: "discord aster token holder cüzdan wallet verify bot doğrulama on-chain rol role 代币 验证 ウォレット",
    a: {
      tr: "Bazı Discord rolleri cüzdan doğrulamasıyla gelir — en bilinen örnek @ASTER rolü. Genel akış: StandX Discord'a katıl → ilgili kanala gir (ör. aster-holders) → resmî bot veya \"Let's go!\" benzeri bağlantıyla cüzdanını bağla → minimum token bakiyesini kanıtla → rol otomatik atanır. Minimum miktar ve süre her etkinlikte duyuruda yazar; süresi dolmuş etkinliklerde rol alınamaz. Cüzdanını asla resmî olmayan bir siteye bağlama.",
      en: "Some Discord roles come through wallet verification — the best-known example is @ASTER. The usual flow: join StandX Discord → enter the relevant channel (e.g. aster-holders) → connect your wallet via the official bot or a \"Let's go!\" style link → prove the minimum token balance → the role is assigned automatically. Minimum amount and deadline are stated in each event announcement; expired events no longer grant the role. Never connect your wallet to an unofficial site.",
      fr: "Certains rôles Discord passent par une vérification de portefeuille — l'exemple le plus connu est @ASTER. Flux habituel : rejoindre le Discord StandX → entrer dans le salon concerné (ex. aster-holders) → connecter le wallet via le bot officiel ou un lien type « Let's go! » → prouver le solde minimum → le rôle est attribué. Montant minimum et deadline sont dans l'annonce ; les événements expirés ne donnent plus le rôle. Ne connecte jamais ton wallet à un site non officiel.",
      zh: "部分 Discord 角色通过钱包验证获得 —— 最知名的例子是 @ASTER。一般流程：加入 StandX Discord → 进入对应频道（如 aster-holders）→ 通过官方 bot 或 \"Let's go!\" 类链接连接钱包 → 证明最低代币余额 → 角色自动发放。最低数量和截止时间在每次活动公告中说明；过期活动无法再获得角色。切勿将钱包连接到非官方网站。",
      ja: "一部の Discord ロールはウォレット認証で付与されます — 代表例が @ASTER です。一般的な流れ：StandX Discord に参加 → 該当チャンネル（例 aster-holders）へ → 公式 bot または「Let's go!」系リンクでウォレット接続 → 最低トークン残高を証明 → ロール自動付与。最低量と期限は各イベント告知に記載。期限切れイベントでは取得不可。非公式サイトにウォレットを接続しないでください。",
    },
  },
];

/** Suggested questions shown under the assistant, per language. */
export const SUGGESTIONS = {
  tr: ["DUSD getirisi nereden geliyor?", "Discord'da rol nasıl alınır?", "BTC kaç?", "SIP-5 nedir?", "Likidasyon nasıl çalışır?"],
  en: ["Where does DUSD yield come from?", "How do I get a Discord role?", "What's BTC doing?", "What is SIP-5?", "How does liquidation work?"],
  fr: ["D'où vient le rendement DUSD ?", "Comment obtenir un rôle Discord ?", "C’est combien BTC ?", "Qu’est-ce que SIP-5 ?", "Comment marche la liquidation ?"],
  zh: ["DUSD 的收益从哪来？", "Discord 角色怎么获得？", "BTC 现在多少？", "SIP-5 是什么？", "清算怎么运作？"],
  ja: ["DUSD の利回りはどこから？", "Discord ロールの取り方は？", "BTC はいくら？", "SIP-5 とは？", "清算はどう動く？"],
};
